const initState = {
  user: {},
  dataFetched: false,
  products: [],
  // jwt: null,
  clients: [],
  legalAddress: {},
  deliveryAddresses: [],
  contactInfo: [],
  roles: [],
  pages: [],
  orders: [],
  productsOfOrders: [],
  warehouse: [],
  usersInfo: [],
  usersMainInfo: [],
  productionBatchLog: [],
  reservedProducts: [],
  listOfOrderedProduction: [],
  listOfOrderedProductionOEM: [],
  batchDesigner: [],
  recipeOrders: [],
  filesWarehouse: [],
  filesOrder: [],
  filesProduct: [],
  stockBalance: [],
};

export default initState;
