export const ADD_NEW_PRODUCT_SOCKET = 'ADD_NEW_PRODUCT_SOCKET';
export const NEW_PRODUCT_SOCKET = 'NEW_PRODUCT_SOCKET';

export const UPDATE_PRODUCT_SOCKET = 'UPDATE_PRODUCT_SOCKET';
export const UPD_PRODUCT_SOCKET = 'UPD_PRODUCT_SOCKET';

export const UPDATE_ROLE_SOCKET = 'UPDATE_ROLE_SOCKET';
export const UPDATE_ROLE_ACTIVE_SOCKET = 'UPDATE_ROLE_ACTIVE_SOCKET';
