export const UPDATE_ROLE_SOCKET = 'UPDATE_ROLE_SOCKET';
export const UPDATE_ROLE_ACTIVE_SOCKET = 'UPDATE_ROLE_ACTIVE_SOCKET';

export const ADD_NEW_PRODUCT_SOCKET = 'ADD_NEW_PRODUCT_SOCKET';
export const NEW_PRODUCT_SOCKET = 'NEW_PRODUCT_SOCKET';

export const UPDATE_PRODUCT_SOCKET = 'UPDATE_PRODUCT_SOCKET';
export const UPD_PRODUCT_SOCKET = 'UPD_PRODUCT_SOCKET';

export const ADD_NEW_ORDER_SOCKET = 'ADD_NEW_ORDER_SOCKET';
export const NEW_ORDER_SOCKET = 'NEW_ORDER_SOCKET';

export const ADD_DATASHIP_ORDER_SOCKET = 'ADD_DATASHIP_ORDER_SOCKET';
export const DATASHIP_ORDER_SOCKET = 'DATASHIP_ORDER_SOCKET';

export const UPDATE_STATUS_OF_ORDER_SOCKET = 'UPDATE_STATUS_OF_ORDER_SOCKET';
export const STATUS_OF_ORDER_SOCKET = 'STATUS_OF_ORDER_SOCKET';

export const UPDATE_PRODUCT_OF_ORDER_SOCKET = 'UPDATE_PRODUCT_OF_ORDER_SOCKET';
export const UPDATE_PRODUCT_OF_ORDER_REDUCER_SOCKET =
  'UPDATE_PRODUCT_OF_ORDER_REDUCER_SOCKET';

export const GET_DELETE_PRODUCT_OF_ORDER_SOCKET =
  'GET_DELETE_PRODUCT_OF_ORDER_SOCKET';
export const DELETE_PRODUCT_OF_ORDER_SOCKET = 'DELETE_PRODUCT_OF_ORDER_SOCKET';

export const ADD_NEW_WAREHOUSE_SOCKET = 'ADD_NEW_WAREHOUSE_SOCKET';
export const NEW_WAREHOUSE_SOCKET = 'NEW_WAREHOUSE_SOCKET';

export const ADD_NEW_CLIENT_SOCKET = 'ADD_NEW_CLIENT_SOCKET'; // back -> socket.message
export const NEW_CLIENT_SOCKET = 'NEW_CLIENT_SOCKET'; // socketAction -> reducer

export const UPDATE_CLIENT_SOCKET = 'UPDATE_CLIENT_SOCKET';
export const NEED_UPDATE_CLIENT_SOCKET = 'NEED_UPDATE_CLIENT_SOCKET';

export const ADD_CLIENTS_LEGAL_ADDRESS_SOCKET = 'ADD_CLIENTS_LEGAL_ADDRESS_SOCKET';
export const UPDATE_LEGAL_ADDRESS_SOCKET = 'UPDATE_LEGAL_ADDRESS_SOCKET';
export const ONE_LEGAL_ADDRESS_SOCKET = 'ONE_LEGAL_ADDRESS_SOCKET';

export const ADD_CONTACT_INFO_SOCKET = 'ADD_CONTACT_INFO_SOCKET';
export const NEW_CONTACT_INFO_SOCKET = 'NEW_CONTACT_INFO_SOCKET';

export const ADD_DELIVERY_ADDRESSES_SOCKET = 'ADD_DELIVERY_ADDRESSES_SOCKET';
export const NEW_DELIVERY_ADDRESSES_SOCKET = 'NEW_DELIVERY_ADDRESSES_SOCKET';

export const ADD_NEW_BATCH_OUTSIDE_SOCKET = 'ADD_NEW_BATCH_OUTSIDE_SOCKET';
export const NEW_BATCH_OUTSIDE_SOCKET = 'NEW_BATCH_OUTSIDE_SOCKET';

export const UPDATE_BATCH_OUTSIDE_SOCKET = 'UPDATE_BATCH_OUTSIDE_SOCKET';
export const NEED_UPDATE_BATCH_OUTSIDE_SOCKET = 'NEED_UPDATE_BATCH_OUTSIDE_SOCKET';

export const DELETE_BATCH_OUTSIDE_SOCKET = 'DELETE_BATCH_OUTSIDE_SOCKET';
export const NEED_DELETE_BATCH_OUTSIDE_SOCKET = 'NEED_DELETE_BATCH_OUTSIDE_SOCKET';

export const GET_DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const UPDATE_REMAINING_STOCK_SOCKET = 'UPDATE_REMAINING_STOCK_SOCKET';
export const REMAINING_STOCK_SOCKET = 'REMAINING_STOCK_SOCKET';

export const ADD_NEW_RECIPE_SOCKET = 'ADD_NEW_RECIPE_SOCKET';
export const NEW_RECIPE_SOCKET = 'NEW_RECIPE_SOCKET';

export const DELETE_RECIPE_SOCKET = 'DELETE_RECIPE_SOCKET';
export const NEED_DELETE_RECIPE_SOCKET = 'NEED_DELETE_RECIPE_SOCKET';
