export const UPDATE_ROLE_SOCKET = 'UPDATE_ROLE_SOCKET';
export const UPDATE_ROLE_ACTIVE_SOCKET = 'UPDATE_ROLE_ACTIVE_SOCKET';

export const ADD_NEW_PRODUCT_SOCKET = 'ADD_NEW_PRODUCT_SOCKET';
export const NEW_PRODUCT_SOCKET = 'NEW_PRODUCT_SOCKET';

export const ADD_NEW_ALDABARAN_SOCKET = 'ADD_NEW_ALDABARAN_SOCKET';
export const NEW_ALDABARAN_SOCKET = 'NEW_ALDABARAN_SOCKET';

export const UPDATE_PRODUCT_SOCKET = 'UPDATE_PRODUCT_SOCKET';
export const UPD_PRODUCT_SOCKET = 'UPD_PRODUCT_SOCKET';

export const REPAIR_PRODUCT_SOCKET = 'REPAIR_PRODUCT_SOCKET';
export const REP_PRODUCT_SOCKET = 'REP_PRODUCT_SOCKET';

export const ADD_NEW_ORDER_SOCKET = 'ADD_NEW_ORDER_SOCKET';
export const NEW_ORDER_SOCKET = 'NEW_ORDER_SOCKET';

export const GET_DELETE_ORDER_SOCKET = 'GET_DELETE_ORDER_SOCKET';
export const DELETE_ORDER_SOCKET = 'DELETE_ORDER_SOCKET';

export const ADD_NEW_DELIVERY_PRICE_SOCKET = 'ADD_NEW_DELIVERY_PRICE_SOCKET';
export const NEW_DELIVERY_PRICE_SOCKET = 'NEW_DELIVERY_PRICE_SOCKET';

export const ADD_DATASHIP_ORDER_SOCKET = 'ADD_DATASHIP_ORDER_SOCKET';
export const DATASHIP_ORDER_SOCKET = 'DATASHIP_ORDER_SOCKET';

export const GET_UPDATE_CONTACT_OF_ORDER_SOCKET =
  'GET_UPDATE_CONTACT_OF_ORDER_SOCKET';
export const UPDATE_CONTACT_OF_ORDER_SOCKET = 'UPDATE_CONTACT_OF_ORDER_SOCKET';

export const GET_UPDATE_ADRESS_OF_ORDER_SOCKET = 'GET_UPDATE_ADRESS_OF_ORDER_SOCKET';
export const UPDATE_ADRESS_OF_ORDER_SOCKET = 'UPDATE_ADRESS_OF_ORDER_SOCKET';

export const ADD_DESCRIPTIOM_ORDER_SOCKET = 'ADD_DESCRIPTIOM_ORDER_SOCKET';
export const DESCRIPTIOM_ORDER_SOCKET = 'DESCRIPTIOM_ORDER_SOCKET';

export const ADD_SECONDARY_CONTACT_ORDER_SOCKET =
  'ADD_SECONDARY_CONTACT_ORDER_SOCKET';
export const SECONDARY_CONTACT_ORDER_SOCKET = 'SECONDARY_CONTACT_ORDER_SOCKET';
export const DELETE_SECONDARY_CONTACT_ORDER_SOCKET =
  'DELETE_SECONDARY_CONTACT_ORDER_SOCKET';
export const REMOVE_SECONDARY_CONTACT_ORDER_SOCKET =
  'REMOVE_SECONDARY_CONTACT_ORDER_SOCKET';

export const UPDATE_STATUS_OF_ORDER_SOCKET = 'UPDATE_STATUS_OF_ORDER_SOCKET';
export const STATUS_OF_ORDER_SOCKET = 'STATUS_OF_ORDER_SOCKET';

export const UPDATE_PERSON_IN_CHARGE_OF_ORDER_SOCKET =
  'UPDATE_PERSON_IN_CHARGE_OF_ORDER_SOCKET';
export const PERSON_IN_CHARGE_OF_ORDER_SOCKET = 'PERSON_IN_CHARGE_OF_ORDER_SOCKET';

export const UPDATE_PRODUCT_OF_ORDER_SOCKET = 'UPDATE_PRODUCT_OF_ORDER_SOCKET';
export const UPDATE_PRODUCT_OF_ORDER_REDUCER_SOCKET =
  'UPDATE_PRODUCT_OF_ORDER_REDUCER_SOCKET';

export const UPDATE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET =
  'UPDATE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET';
export const UPDATE_DRY_MIXED_PRODUCT_OF_ORDER_REDUCER_SOCKET =
  'UPDATE_DRY_MIXED_PRODUCT_OF_ORDER_REDUCER_SOCKET';

export const UPDATE_ANCHOR_PRODUCT_OF_ORDER_SOCKET =
  'UPDATE_ANCHOR_PRODUCT_OF_ORDER_SOCKET';
export const UPDATE_ANCHOR_PRODUCT_OF_ORDER_REDUCER_SOCKET =
  'UPDATE_ANCHOR_PRODUCT_OF_ORDER_REDUCER_SOCKET';

export const UPDATE_TOOL_PRODUCT_OF_ORDER_SOCKET =
  'UPDATE_TOOL_PRODUCT_OF_ORDER_SOCKET';
export const UPDATE_TOOL_PRODUCT_OF_ORDER_REDUCER_SOCKET =
  'UPDATE_TOOL_PRODUCT_OF_ORDER_REDUCER_SOCKET';

export const UPDATE_REL_MAT_PRODUCT_OF_ORDER_SOCKET =
  'UPDATE_REL_MAT_PRODUCT_OF_ORDER_SOCKET';
export const UPDATE_REL_MAT_PRODUCT_OF_ORDER_REDUCER_SOCKET =
  'UPDATE_REL_MAT_PRODUCT_OF_ORDER_REDUCER_SOCKET';

export const GET_DELETE_PRODUCT_OF_ORDER_SOCKET =
  'GET_DELETE_PRODUCT_OF_ORDER_SOCKET';
export const DELETE_PRODUCT_OF_ORDER_SOCKET = 'DELETE_PRODUCT_OF_ORDER_SOCKET';

export const GET_DELETE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET =
  'GET_DELETE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET';
export const DELETE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET =
  'DELETE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET';

export const GET_DELETE_ANCHOR_PRODUCT_OF_ORDER_SOCKET =
  'GET_DELETE_ANCHOR_PRODUCT_OF_ORDER_SOCKET';
export const DELETE_ANCHOR_PRODUCT_OF_ORDER_SOCKET =
  'DELETE_ANCHOR_PRODUCT_OF_ORDER_SOCKET';

export const GET_DELETE_TOOL_PRODUCT_OF_ORDER_SOCKET =
  'GET_DELETE_TOOL_PRODUCT_OF_ORDER_SOCKET';
export const DELETE_TOOL_PRODUCT_OF_ORDER_SOCKET =
  'DELETE_TOOL_PRODUCT_OF_ORDER_SOCKET';

export const GET_DELETE_REL_MAT_PRODUCT_OF_ORDER_SOCKET =
  'GET_DELETE_REL_MAT_PRODUCT_OF_ORDER_SOCKET';
export const DELETE_REL_MAT_PRODUCT_OF_ORDER_SOCKET =
  'DELETE_REL_MAT_PRODUCT_OF_ORDER_SOCKET';

export const GET_UPDATE_PRODUCT_INFO_OF_ORDER_SOCKET =
  'GET_UPDATE_PRODUCT_INFO_OF_ORDER_SOCKET';
export const UPDATE_PRODUCT_INFO_OF_ORDER_SOCKET =
  'UPDATE_PRODUCT_INFO_OF_ORDER_SOCKET';

export const GET_UPDATE_DRY_MIXED_PRODUCT_INFO_OF_ORDER_SOCKET =
  'GET_UPDATE_DRY_MIXED_PRODUCT_INFO_OF_ORDER_SOCKET';
export const UPDATE_DRY_MIXED_PRODUCT_INFO_OF_ORDER_SOCKET =
  'UPDATE_DRY_MIXED_PRODUCT_INFO_OF_ORDER_SOCKET';

export const GET_UPDATE_ANCHOR_PRODUCT_INFO_OF_ORDER_SOCKET =
  'GET_UPDATE_ANCHOR_PRODUCT_INFO_OF_ORDER_SOCKET';
export const UPDATE_ANCHOR_PRODUCT_INFO_OF_ORDER_SOCKET =
  'UPDATE_ANCHOR_PRODUCT_INFO_OF_ORDER_SOCKET';

export const GET_UPDATE_TOOL_PRODUCT_INFO_OF_ORDER_SOCKET =
  'GET_UPDATE_TOOL_PRODUCT_INFO_OF_ORDER_SOCKET';
export const UPDATE_TOOL_PRODUCT_INFO_OF_ORDER_SOCKET =
  'UPDATE_TOOL_PRODUCT_INFO_OF_ORDER_SOCKET';

export const GET_UPDATE_REL_MAT_PRODUCT_INFO_OF_ORDER_SOCKET =
  'GET_UPDATE_REL_MAT_PRODUCT_INFO_OF_ORDER_SOCKET';
export const UPDATE_REL_MAT_PRODUCT_INFO_OF_ORDER_SOCKET =
  'UPDATE_REL_MAT_PRODUCT_INFO_OF_ORDER_SOCKET';

export const ADD_NEW_WAREHOUSE_SOCKET = 'ADD_NEW_WAREHOUSE_SOCKET';
export const NEW_WAREHOUSE_SOCKET = 'NEW_WAREHOUSE_SOCKET';

export const ADD_NEW_CLIENT_SOCKET = 'ADD_NEW_CLIENT_SOCKET'; // back -> socket.message
export const NEW_CLIENT_SOCKET = 'NEW_CLIENT_SOCKET'; // socketAction -> reducer

export const UPDATE_CLIENT_SOCKET = 'UPDATE_CLIENT_SOCKET';
export const NEED_UPDATE_CLIENT_SOCKET = 'NEED_UPDATE_CLIENT_SOCKET';

export const ADD_CLIENTS_LEGAL_ADDRESS_SOCKET = 'ADD_CLIENTS_LEGAL_ADDRESS_SOCKET';
export const UPDATE_LEGAL_ADDRESS_SOCKET = 'UPDATE_LEGAL_ADDRESS_SOCKET';
export const ONE_LEGAL_ADDRESS_SOCKET = 'ONE_LEGAL_ADDRESS_SOCKET';

export const ADD_CONTACT_INFO_SOCKET = 'ADD_CONTACT_INFO_SOCKET';
export const NEW_CONTACT_INFO_SOCKET = 'NEW_CONTACT_INFO_SOCKET';

export const UPDATE_CONTACT_INFO_SOCKET = 'UPDATE_CONTACT_INFO_SOCKET';
export const NEED_UPDATE_CONTACT_INFO_SOCKET = 'NEED_UPDATE_CONTACT_INFO_SOCKET';

export const NEED_UPD_CONTACT_PRICE_INFO_SOCKET =
  'NEED_UPD_CONTACT_PRICE_INFO_SOCKET';
export const UPD_CONTACT_PRICE_INFO_SOCKET = 'UPD_CONTACT_PRICE_INFO_SOCKET';

export const ADD_DELIVERY_ADDRESSES_SOCKET = 'ADD_DELIVERY_ADDRESSES_SOCKET';
export const NEW_DELIVERY_ADDRESSES_SOCKET = 'NEW_DELIVERY_ADDRESSES_SOCKET';

export const UPDATE_DELIVERY_ADDRESSES_SOCKET = 'UPDATE_DELIVERY_ADDRESSES_SOCKET';
export const NEED_UPDATE_DELIVERY_ADDRESSES_SOCKET =
  'NEED_UPDATE_DELIVERY_ADDRESSES_SOCKET';

export const ADD_NEW_BATCH_OUTSIDE_SOCKET = 'ADD_NEW_BATCH_OUTSIDE_SOCKET';
export const NEW_BATCH_OUTSIDE_SOCKET = 'NEW_BATCH_OUTSIDE_SOCKET';

export const UPDATE_BATCH_OUTSIDE_SOCKET = 'UPDATE_BATCH_OUTSIDE_SOCKET';
export const NEED_UPDATE_BATCH_OUTSIDE_SOCKET = 'NEED_UPDATE_BATCH_OUTSIDE_SOCKET';

export const DELETE_BATCH_OUTSIDE_SOCKET = 'DELETE_BATCH_OUTSIDE_SOCKET';
export const NEED_DELETE_BATCH_OUTSIDE_SOCKET = 'NEED_DELETE_BATCH_OUTSIDE_SOCKET';

export const GET_NEW_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_NEW_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const NEW_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'NEW_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_UPDATE_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_UPDATE_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const UPDATE_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'UPDATE_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_NEW_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_NEW_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const NEW_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'NEW_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_UPDATE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_UPDATE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const UPDATE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'UPDATE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_DELETE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_DELETE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const DELETE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'DELETE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_NEW_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_NEW_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const NEW_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'NEW_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_UPDATE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_UPDATE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const UPDATE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'UPDATE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_DELETE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_DELETE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const DELETE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'DELETE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_NEW_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_NEW_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const NEW_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'NEW_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_UPDATE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_UPDATE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const UPDATE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'UPDATE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_DELETE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_DELETE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const DELETE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'DELETE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_NEW_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_NEW_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const NEW_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'NEW_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_UPDATE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_UPDATE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const UPDATE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'UPDATE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const GET_DELETE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_DELETE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET';
export const DELETE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'DELETE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET';

export const UPDATE_REMAINING_STOCK_SOCKET = 'UPDATE_REMAINING_STOCK_SOCKET';
export const REMAINING_STOCK_SOCKET = 'REMAINING_STOCK_SOCKET';

export const UPDATE_WAREHOUSE_QUANTITYS_SOCKET = 'UPDATE_WAREHOUSE_QUANTITYS_SOCKET';
export const WAREHOUSE_QUANTITYS_SOCKET = 'WAREHOUSE_QUANTITYS_SOCKET';

export const UPDATE_DRY_MIXES_QUANTITYS_SOCKET = 'UPDATE_DRY_MIXES_QUANTITYS_SOCKET';
export const DRY_MIXES_QUANTITYS_SOCKET = 'DRY_MIXES_QUANTITYS_SOCKET';

export const UPDATE_ANCHOR_QUANTITYS_SOCKET = 'UPDATE_ANCHOR_QUANTITYS_SOCKET';
export const ANCHOR_QUANTITYS_SOCKET = 'ANCHOR_QUANTITYS_SOCKET';

export const UPDATE_TOOL_QUANTITYS_SOCKET = 'UPDATE_TOOL_QUANTITYS_SOCKET';
export const TOOL_QUANTITYS_SOCKET = 'TOOL_QUANTITYS_SOCKET';

export const UPDATE_REL_MAT_QUANTITYS_SOCKET = 'UPDATE_REL_MAT_QUANTITYS_SOCKET';
export const REL_MAT_QUANTITYS_SOCKET = 'REL_MAT_QUANTITYS_SOCKET';

export const ADD_NEW_RECIPE_SOCKET = 'ADD_NEW_RECIPE_SOCKET';
export const NEW_RECIPE_SOCKET = 'NEW_RECIPE_SOCKET';

export const ADD_NEW_RAW_MAT_CONSUMPTION_SOCKET =
  'ADD_NEW_RAW_MAT_CONSUMPTION_SOCKET';
export const NEW_RAW_MAT_CONSUMPTION_SOCKET = 'NEW_RAW_MAT_CONSUMPTION_SOCKET';

export const UPDATE_RAW_MAT_CONSUMPTION_SOCKET = 'UPDATE_RAW_MAT_CONSUMPTION_SOCKET';
export const UPDT_RAW_MAT_CONSUMPTION_SOCKET = 'UPDT_RAW_MAT_CONSUMPTION_SOCKET';

export const DELETE_OLD_RAW_MAT_CONSUMPTION_SOCKET =
  'DELETE_OLD_RAW_MAT_CONSUMPTION_SOCKET';
export const DELETE_RAW_MAT_CONSUMPTION_SOCKET = 'DELETE_RAW_MAT_CONSUMPTION_SOCKET';

export const ADD_NEW_RAW_MAT_CONSUMPTION_CURRENT_MOLDS_SOCKET =
  'ADD_NEW_RAW_MAT_CONSUMPTION_CURRENT_MOLDS_SOCKET';
export const NEW_RAW_MAT_CONSUMPTION_CURRENT_MOLDS_SOCKET =
  'NEW_RAW_MAT_CONSUMPTION_CURRENT_MOLDS_SOCKET';

export const DELETE_OLD_RAW_MAT_CONSUMPTION_CURRENT_MOLDS_SOCKET =
  'DELETE_OLD_RAW_MAT_CONSUMPTION_CURRENT_MOLDS_SOCKET';
export const DELETE_RAW_MAT_CONSUMPTION_CURRENT_MOLDS_SOCKET =
  'DELETE_RAW_MAT_CONSUMPTION_CURRENT_MOLDS_SOCKET';

export const DELETE_RECIPE_SOCKET = 'DELETE_RECIPE_SOCKET';
export const NEED_DELETE_RECIPE_SOCKET = 'NEED_DELETE_RECIPE_SOCKET';

export const ADD_NEW_FILES_WAREHOUSE_SOCKET = 'ADD_NEW_FILES_WAREHOUSE_SOCKET';
export const NEW_FILES_WAREHOUSE_SOCKET = 'NEW_FILES_WAREHOUSE_SOCKET';

export const DELETE_FILES_WAREHOUSE_SOCKET = 'DELETE_FILES_WAREHOUSE_SOCKET';
export const NEED_DELETE_FILES_WAREHOUSE_SOCKET =
  'NEED_DELETE_FILES_WAREHOUSE_SOCKET';

export const ADD_NEW_FILES_ORDER_SOCKET = 'ADD_NEW_FILES_ORDER_SOCKET';
export const NEW_FILES_ORDER_SOCKET = 'NEW_FILES_ORDER_SOCKET';

export const DELETE_FILES_ORDER_SOCKET = 'DELETE_FILES_ORDER_SOCKET';
export const NEED_DELETE_FILES_ORDER_SOCKET = 'NEED_DELETE_FILES_ORDER_SOCKET';

export const ADD_NEW_FILES_LOTES_LIST_SOCKET = 'ADD_NEW_FILES_LOTES_LIST_SOCKET';
export const NEW_FILES_LOTES_LIST_SOCKET = 'NEW_FILES_LOTES_LIST_SOCKET';

export const DELETE_FILES_LOTES_LIST_SOCKET = 'DELETE_FILES_LOTES_LIST_SOCKET';
export const NEED_DELETE_FILES_LOTES_LIST_SOCKET =
  'NEED_DELETE_FILES_LOTES_LIST_SOCKET';

export const SAVE_MATERIAL_PLAN_SOCKET = 'SAVE_MATERIAL_PLAN_SOCKET';
export const NEW_MATERIAL_PLAN_SOCKET = 'NEW_MATERIAL_PLAN_SOCKET';

export const DELETE_MATERIAL_PLAN_SOCKET = 'DELETE_MATERIAL_PLAN_SOCKET';
export const NEES_DELETE_MATERIAL_PLAN_SOCKET = 'NEES_DELETE_MATERIAL_PLAN_SOCKET';

export const ADD_NEW_FILES_PRODUCT_SOCKET = 'ADD_NEW_FILES_PRODUCT_SOCKET';
export const NEW_FILES_PRODUCT_SOCKET = 'NEW_FILES_PRODUCT_SOCKET';

export const DELETE_FILES_PRODUCT_SOCKET = 'DELETE_FILES_PRODUCT_SOCKET';
export const NEED_DELETE_FILES_PRODUCT_SOCKET = 'NEED_DELETE_FILES_PRODUCT_SOCKET';

export const ADD_NEW_STOCK_BALANCE_SOCKET = 'ADD_NEW_STOCK_BALANCE_SOCKET';
export const NEW_STOCK_BALANCE_SOCKET = 'NEW_STOCK_BALANCE_SOCKET';

export const ADD_NEW_DRY_MIXES_JOURNAL_SOCKET = 'ADD_NEW_DRY_MIXES_JOURNAL_SOCKET';
export const NEW_DRY_MIXES_JOURNAL_SOCKET = 'NEW_DRY_MIXES_JOURNAL_SOCKET';

export const UPDATE_DRY_MIXES_JOURNAL_SOCKET = 'UPDATE_DRY_MIXES_JOURNAL_SOCKET';
export const NEED_UPDATE_DRY_MIXES_JOURNAL_SOCKET =
  'NEED_UPDATE_DRY_MIXES_JOURNAL_SOCKET';

export const ADD_NEW_RELATED_MATERIALS_JOURNAL_SOCKET =
  'ADD_NEW_RELATED_MATERIALS_JOURNAL_SOCKET';
export const NEW_RELATED_MATERIALS_JOURNAL_SOCKET =
  'NEW_RELATED_MATERIALS_JOURNAL_SOCKET';

export const UPDATE_RELATED_MATERIALS_JOURNAL_SOCKET =
  'UPDATE_RELATED_MATERIALS_JOURNAL_SOCKET';
export const NEED_UPDATE_RELATED_MATERIALS_JOURNAL_SOCKET =
  'NEED_UPDATE_RELATED_MATERIALS_JOURNAL_SOCKET';

export const ADD_NEW_ANCHOR_SOCKET = 'ADD_NEW_ANCHOR_SOCKET';
export const NEW_ANCHOR_SOCKET = 'NEW_ANCHOR_SOCKET';

export const UPDATE_ANCHOR_SOCKET = 'UPDATE_ANCHOR_SOCKET';
export const NEED_UPDATE_ANCHOR_SOCKET = 'NEED_UPDATE_ANCHOR_SOCKET';

export const ADD_NEW_TOOL_SOCKET = 'ADD_NEW_TOOL_SOCKET';
export const NEW_TOOL_SOCKET = 'NEW_TOOL_SOCKET';

export const UPDATE_TOOL_SOCKET = 'UPDATE_TOOL_SOCKET';
export const NEED_UPDATE_TOOL_SOCKET = 'NEED_UPDATE_TOOL_SOCKET';

export const ADD_NEW_DRY_MIXES_WAREHOUSE_SOCKET =
  'ADD_NEW_DRY_MIXES_WAREHOUSE_SOCKET';
export const NEW_DRY_MIXES_WAREHOUSE_SOCKET = 'NEW_DRY_MIXES_WAREHOUSE_SOCKET';

export const UPDATE_DRY_MIXES_WAREHOUSE_SOCKET = 'UPDATE_DRY_MIXES_WAREHOUSE_SOCKET';
export const NEED_UPDATE_DRY_MIXES_WAREHOUSE_SOCKET =
  'NEED_UPDATE_DRY_MIXES_WAREHOUSE_SOCKET';

export const ADD_NEW_RELATED_MATERIALS_WAREHOUSE_SOCKET =
  'ADD_NEW_RELATED_MATERIALS_WAREHOUSE_SOCKET';
export const NEW_RELATED_MATERIALS_WAREHOUSE_SOCKET =
  'NEW_RELATED_MATERIALS_WAREHOUSE_SOCKET';

export const UPDATE_RELATED_MATERIALS_WAREHOUSE_SOCKET =
  'UPDATE_RELATED_MATERIALS_WAREHOUSE_SOCKET';
export const NEED_UPDATE_RELATED_MATERIALS_WAREHOUSE_SOCKET =
  'NEED_UPDATE_RELATED_MATERIALS_WAREHOUSE_SOCKET';

export const ADD_NEW_ANCHORS_WAREHOUSE_SOCKET = 'ADD_NEW_ANCHORS_WAREHOUSE_SOCKET';
export const NEW_ANCHORS_WAREHOUSE_SOCKET = 'NEW_ANCHORS_WAREHOUSE_SOCKET';

export const UPDATE_ANCHORS_WAREHOUSE_SOCKET = 'UPDATE_ANCHORS_WAREHOUSE_SOCKET';
export const NEED_UPDATE_ANCHORS_WAREHOUSE_SOCKET =
  'NEED_UPDATE_ANCHORS_WAREHOUSE_SOCKET';

export const ADD_NEW_TOOLS_WAREHOUSE_SOCKET = 'ADD_NEW_TOOLS_WAREHOUSE_SOCKET';
export const NEW_TOOLS_WAREHOUSE_SOCKET = 'NEW_TOOLS_WAREHOUSE_SOCKET';

export const UPDATE_TOOLS_WAREHOUSE_SOCKET = 'UPDATE_TOOLS_WAREHOUSE_SOCKET';
export const NEED_UPDATE_TOOLS_WAREHOUSE_SOCKET =
  'NEED_UPDATE_TOOLS_WAREHOUSE_SOCKET';

export const UPDATE_RAW_MATERIALS_WAREHOUSE_SOCKET =
  'UPDATE_RAW_MATERIALS_WAREHOUSE_SOCKET';
export const NEED_UPDATE_RAW_MATERIALS_WAREHOUSE_SOCKET =
  'NEED_UPDATE_RAW_MATERIALS_WAREHOUSE_SOCKET';

export const ADD_NEW_QUALITY_MANAGEMENT_DATA_SOCKET =
  'ADD_NEW_QUALITY_MANAGEMENT_DATA_SOCKET';
export const NEW_QUALITY_MANAGEMENT_DATA_SOCKET =
  'NEW_QUALITY_MANAGEMENT_DATA_SOCKET';

export const UPDATE_QUALITY_MANAGEMENT_DATA_SOCKET =
  'UPDATE_QUALITY_MANAGEMENT_DATA_SOCKET';
export const NEED_UPDATE_QUALITY_MANAGEMENT_DATA_SOCKET =
  'NEED_UPDATE_QUALITY_MANAGEMENT_DATA_SOCKET';

export const DELETE_QUALITY_MANAGEMENT_DATA_SOCKET =
  'DELETE_QUALITY_MANAGEMENT_DATA_SOCKET';
export const NEED_DELETE_QUALITY_MANAGEMENT_DATA_SOCKET =
  'NEED_DELETE_QUALITY_MANAGEMENT_DATA_SOCKET';

export const ADD_NEW_RELATED_MATERIALS_BACKORDER_SOCKET =
  'ADD_NEW_RELATED_MATERIALS_BACKORDER_SOCKET';
export const NEW_RELATED_MATERIALS_BACKORDER_SOCKET =
  'NEW_RELATED_MATERIALS_BACKORDER_SOCKET';

export const UPDATE_RELATED_MATERIALS_BACKORDER_SOCKET =
  'UPDATE_RELATED_MATERIALS_BACKORDER_SOCKET';
export const NEED_UPDATE_RELATED_MATERIALS_BACKORDER_SOCKET =
  'NEED_UPDATE_RELATED_MATERIALS_BACKORDER_SOCKET';

export const UPDATE_PRODUCT_CODE_SOCKET = 'UPDATE_PRODUCT_CODE_SOCKET';
export const NEED_UPDATE_PRODUCT_CODE_SOCKET = 'NEED_UPDATE_PRODUCT_CODE_SOCKET';

export const ADD_RANDOM_PRODUCTS_OF_ORDER_SOCKET =
  'ADD_RANDOM_PRODUCTS_OF_ORDER_SOCKET';
export const NEW_RANDOM_PRODUCTS_OF_ORDER_SOCKET =
  'NEW_RANDOM_PRODUCTS_OF_ORDER_SOCKET';

export const GET_UPDATE_AUTOCLAVE_CALENDAR_SOCKET =
  'GET_UPDATE_AUTOCLAVE_CALENDAR_SOCKET';
export const UPDATE_AUTOCLAVE_CALENDAR_SOCKET = 'UPDATE_AUTOCLAVE_CALENDAR_SOCKET';

export const ADD_NEW_LIST_OF_ORDERED_PRODUCTION_SOCKET =
  'ADD_NEW_LIST_OF_ORDERED_PRODUCTION_SOCKET';
export const NEW_LIST_OF_ORDERED_PRODUCTION_SOCKET =
  'NEW_LIST_OF_ORDERED_PRODUCTION_SOCKET';

export const GET_UPDATE_LIST_OF_ORDERED_PRODUCTION_SOCKET =
  'GET_UPDATE_LIST_OF_ORDERED_PRODUCTION_SOCKET';
export const UPDATE_LIST_OF_ORDERED_PRODUCTION_SOCKET =
  'UPDATE_LIST_OF_ORDERED_PRODUCTION_SOCKET';

export const ADD_NEW_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET =
  'ADD_NEW_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET';
export const NEW_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET =
  'NEW_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET';

export const GET_UPDATE_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET =
  'GET_UPDATE_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET';
export const UPDATE_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET =
  'UPDATE_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET';
export const ADD_NEW_WAREHOUSE_SAND_SOCKET = 'ADD_NEW_WAREHOUSE_SAND_SOCKET';
export const NEW_WAREHOUSE_SAND_SOCKET = 'NEW_WAREHOUSE_SAND_SOCKET';
export const UPDATE_WAREHOUSE_SAND_SOCKET = 'UPDATE_WAREHOUSE_SAND_SOCKET';
export const NEED_UPDATE_WAREHOUSE_SAND_SOCKET = 'NEED_UPDATE_WAREHOUSE_SAND_SOCKET';
export const DELETE_WAREHOUSE_SAND_SOCKET = 'DELETE_WAREHOUSE_SAND_SOCKET';
export const NEED_DELETE_WAREHOUSE_SAND_SOCKET = 'NEED_DELETE_WAREHOUSE_SAND_SOCKET';

export const ADD_NEW_WAREHOUSE_LIME_SOCKET = 'ADD_NEW_WAREHOUSE_LIME_SOCKET';
export const NEW_WAREHOUSE_LIME_SOCKET = 'NEW_WAREHOUSE_LIME_SOCKET';
export const UPDATE_WAREHOUSE_LIME_SOCKET = 'UPDATE_WAREHOUSE_LIME_SOCKET';
export const NEED_UPDATE_WAREHOUSE_LIME_SOCKET = 'NEED_UPDATE_WAREHOUSE_LIME_SOCKET';
export const DELETE_WAREHOUSE_LIME_SOCKET = 'DELETE_WAREHOUSE_LIME_SOCKET';
export const NEED_DELETE_WAREHOUSE_LIME_SOCKET = 'NEED_DELETE_WAREHOUSE_LIME_SOCKET';

export const ADD_NEW_WAREHOUSE_CEMENT_SOCKET = 'ADD_NEW_WAREHOUSE_CEMENT_SOCKET';
export const NEW_WAREHOUSE_CEMENT_SOCKET = 'NEW_WAREHOUSE_CEMENT_SOCKET';
export const UPDATE_WAREHOUSE_CEMENT_SOCKET = 'UPDATE_WAREHOUSE_CEMENT_SOCKET';
export const NEED_UPDATE_WAREHOUSE_CEMENT_SOCKET =
  'NEED_UPDATE_WAREHOUSE_CEMENT_SOCKET';
export const DELETE_WAREHOUSE_CEMENT_SOCKET = 'DELETE_WAREHOUSE_CEMENT_SOCKET';
export const NEED_DELETE_WAREHOUSE_CEMENT_SOCKET =
  'NEED_DELETE_WAREHOUSE_CEMENT_SOCKET';

export const ADD_NEW_WAREHOUSE_GYPSUM_SOCKET = 'ADD_NEW_WAREHOUSE_GYPSUM_SOCKET';
export const NEW_WAREHOUSE_GYPSUM_SOCKET = 'NEW_WAREHOUSE_GYPSUM_SOCKET';
export const UPDATE_WAREHOUSE_GYPSUM_SOCKET = 'UPDATE_WAREHOUSE_GYPSUM_SOCKET';
export const NEED_UPDATE_WAREHOUSE_GYPSUM_SOCKET =
  'NEED_UPDATE_WAREHOUSE_GYPSUM_SOCKET';
export const DELETE_WAREHOUSE_GYPSUM_SOCKET = 'DELETE_WAREHOUSE_GYPSUM_SOCKET';
export const NEED_DELETE_WAREHOUSE_GYPSUM_SOCKET =
  'NEED_DELETE_WAREHOUSE_GYPSUM_SOCKET';

export const ADD_NEW_WAREHOUSE_GYPSUM_STONE_SOCKET =
  'ADD_NEW_WAREHOUSE_GYPSUM_STONE_SOCKET';
export const NEW_WAREHOUSE_GYPSUM_STONE_SOCKET = 'NEW_WAREHOUSE_GYPSUM_STONE_SOCKET';
export const UPDATE_WAREHOUSE_GYPSUM_STONE_SOCKET =
  'UPDATE_WAREHOUSE_GYPSUM_STONE_SOCKET';
export const NEED_UPDATE_WAREHOUSE_GYPSUM_STONE_SOCKET =
  'NEED_UPDATE_WAREHOUSE_GYPSUM_STONE_SOCKET';
export const DELETE_WAREHOUSE_GYPSUM_STONE_SOCKET =
  'DELETE_WAREHOUSE_GYPSUM_STONE_SOCKET';
export const NEED_DELETE_WAREHOUSE_GYPSUM_STONE_SOCKET =
  'NEED_DELETE_WAREHOUSE_GYPSUM_STONE_SOCKET';

export const ADD_NEW_WAREHOUSE_ALUMINUM1_SOCKET =
  'ADD_NEW_WAREHOUSE_ALUMINUM1_SOCKET';
export const NEW_WAREHOUSE_ALUMINUM1_SOCKET = 'NEW_WAREHOUSE_ALUMINUM1_SOCKET';
export const UPDATE_WAREHOUSE_ALUMINUM1_SOCKET = 'UPDATE_WAREHOUSE_ALUMINUM1_SOCKET';
export const NEED_UPDATE_WAREHOUSE_ALUMINUM1_SOCKET =
  'NEED_UPDATE_WAREHOUSE_ALUMINUM1_SOCKET';
export const DELETE_WAREHOUSE_ALUMINUM1_SOCKET = 'DELETE_WAREHOUSE_ALUMINUM1_SOCKET';
export const NEED_DELETE_WAREHOUSE_ALUMINUM1_SOCKET =
  'NEED_DELETE_WAREHOUSE_ALUMINUM1_SOCKET';

export const ADD_NEW_WAREHOUSE_ALUMINUM2_SOCKET =
  'ADD_NEW_WAREHOUSE_ALUMINUM2_SOCKET';
export const NEW_WAREHOUSE_ALUMINUM2_SOCKET = 'NEW_WAREHOUSE_ALUMINUM2_SOCKET';
export const UPDATE_WAREHOUSE_ALUMINUM2_SOCKET = 'UPDATE_WAREHOUSE_ALUMINUM2_SOCKET';
export const NEED_UPDATE_WAREHOUSE_ALUMINUM2_SOCKET =
  'NEED_UPDATE_WAREHOUSE_ALUMINUM2_SOCKET';
export const DELETE_WAREHOUSE_ALUMINUM2_SOCKET = 'DELETE_WAREHOUSE_ALUMINUM2_SOCKET';
export const NEED_DELETE_WAREHOUSE_ALUMINUM2_SOCKET =
  'NEED_DELETE_WAREHOUSE_ALUMINUM2_SOCKET';

export const ADD_NEW_WAREHOUSE_GRINDING_BALLS_SOCKET =
  'ADD_NEW_WAREHOUSE_GRINDING_BALLS_SOCKET';
export const NEW_WAREHOUSE_GRINDING_BALLS_SOCKET =
  'NEW_WAREHOUSE_GRINDING_BALLS_SOCKET';
export const UPDATE_WAREHOUSE_GRINDING_BALLS_SOCKET =
  'UPDATE_WAREHOUSE_GRINDING_BALLS_SOCKET';
export const NEED_UPDATE_WAREHOUSE_GRINDING_BALLS_SOCKET =
  'NEED_UPDATE_WAREHOUSE_GRINDING_BALLS_SOCKET';
export const DELETE_WAREHOUSE_GRINDING_BALLS_SOCKET =
  'DELETE_WAREHOUSE_GRINDING_BALLS_SOCKET';
export const NEED_DELETE_WAREHOUSE_GRINDING_BALLS_SOCKET =
  'NEED_DELETE_WAREHOUSE_GRINDING_BALLS_SOCKET';

export const ADD_NEW_WAREHOUSE_AAC_SOCKET = 'ADD_NEW_WAREHOUSE_AAC_SOCKET';
export const NEW_WAREHOUSE_AAC_SOCKET = 'NEW_WAREHOUSE_AAC_SOCKET';
export const UPDATE_WAREHOUSE_AAC_SOCKET = 'UPDATE_WAREHOUSE_AAC_SOCKET';
export const NEED_UPDATE_WAREHOUSE_AAC_SOCKET = 'NEED_UPDATE_WAREHOUSE_AAC_SOCKET';
export const DELETE_WAREHOUSE_AAC_SOCKET = 'DELETE_WAREHOUSE_AAC_SOCKET';
export const NEED_DELETE_WAREHOUSE_AAC_SOCKET = 'NEED_DELETE_WAREHOUSE_AAC_SOCKET';

export const ADD_NEW_WAREHOUSE_SAND_SLURRY_SOCKET =
  'ADD_NEW_WAREHOUSE_SAND_SLURRY_SOCKET';
export const NEW_WAREHOUSE_SAND_SLURRY_SOCKET = 'NEW_WAREHOUSE_SAND_SLURRY_SOCKET';
export const UPDATE_WAREHOUSE_SAND_SLURRY_SOCKET =
  'UPDATE_WAREHOUSE_SAND_SLURRY_SOCKET';
export const NEED_UPDATE_WAREHOUSE_SAND_SLURRY_SOCKET =
  'NEED_UPDATE_WAREHOUSE_SAND_SLURRY_SOCKET';

export const ADD_NEW_WAREHOUSE_PALLETS_SOCKET = 'ADD_NEW_WAREHOUSE_PALLETS_SOCKET';
export const NEW_WAREHOUSE_PALLETS_SOCKET = 'NEW_WAREHOUSE_PALLETS_SOCKET';
export const UPDATE_WAREHOUSE_PALLETS_SOCKET = 'UPDATE_WAREHOUSE_PALLETS_SOCKET';
export const NEED_UPDATE_WAREHOUSE_PALLETS_SOCKET =
  'NEED_UPDATE_WAREHOUSE_PALLETS_SOCKET';
export const DELETE_WAREHOUSE_PALLETS_SOCKET = 'DELETE_WAREHOUSE_PALLETS_SOCKET';
export const NEED_DELETE_WAREHOUSE_PALLETS_SOCKET =
  'NEED_DELETE_WAREHOUSE_PALLETS_SOCKET';

export const ADD_NEW_WAREHOUSE_PLASTICS_SOCKET = 'ADD_NEW_WAREHOUSE_PLASTICS_SOCKET';
export const NEW_WAREHOUSE_PLASTICS_SOCKET = 'NEW_WAREHOUSE_PLASTICS_SOCKET';
export const UPDATE_WAREHOUSE_PLASTICS_SOCKET = 'UPDATE_WAREHOUSE_PLASTICS_SOCKET';
export const NEED_UPDATE_WAREHOUSE_PLASTICS_SOCKET =
  'NEED_UPDATE_WAREHOUSE_PLASTICS_SOCKET';
export const DELETE_WAREHOUSE_PLASTICS_SOCKET = 'DELETE_WAREHOUSE_PLASTICS_SOCKET';
export const NEED_DELETE_WAREHOUSE_PLASTICS_SOCKET =
  'NEED_DELETE_WAREHOUSE_PLASTICS_SOCKET';

export const ADD_NEW_WAREHOUSE_SAND_POWDER_SOCKET =
  'ADD_NEW_WAREHOUSE_SAND_POWDER_SOCKET';
export const NEW_WAREHOUSE_SAND_POWDER_SOCKET = 'NEW_WAREHOUSE_SAND_POWDER_SOCKET';
export const UPDATE_WAREHOUSE_SAND_POWDER_SOCKET =
  'UPDATE_WAREHOUSE_SAND_POWDER_SOCKET';
export const NEED_UPDATE_WAREHOUSE_SAND_POWDER_SOCKET =
  'NEED_UPDATE_WAREHOUSE_SAND_POWDER_SOCKET';
export const DELETE_WAREHOUSE_SAND_POWDER_SOCKET =
  'DELETE_WAREHOUSE_SAND_POWDER_SOCKET';
export const NEED_DELETE_WAREHOUSE_SAND_POWDER_SOCKET =
  'NEED_DELETE_WAREHOUSE_SAND_POWDER_SOCKET';

export const ADD_NEW_LOTES_LIST_SOCKET = 'ADD_NEW_LOTES_LIST_SOCKET';
export const NEW_LOTES_LIST_SOCKET = 'NEW_LOTES_LIST_SOCKET';

export const DELETE_LOTES_LIST_CAKES_SOCKET = 'DELETE_LOTES_LIST_CAKES_SOCKET';
export const DELETE_LAST_LOTES_LIST_CAKES_SOCKET =
  'DELETE_LAST_LOTES_LIST_CAKES_SOCKET';

export const UPDATE_LOTES_LIST_SOCKET = 'UPDATE_LOTES_LIST_SOCKET';
export const UPD_LOTES_LIST_SOCKET = 'UPD_LOTES_LIST_SOCKET';

export const UPDATE_LOTES_LIST_NOTE_SOCKET = 'UPDATE_LOTES_LIST_NOTE_SOCKET';
export const UPD_LOTES_LIST_NOTE_SOCKET = 'UPD_LOTES_LIST_NOTE_SOCKET';

export const ADD_NEW_LOTES_LIST_CAKES_SOCKET = 'ADD_NEW_LOTES_LIST_CAKES_SOCKET';
export const NEW_LOTES_LIST_CAKES_SOCKET = 'NEW_LOTES_LIST_CAKES_SOCKET';

export const UPDATE_LOTES_LIST_CAKES_SOCKET = 'UPDATE_LOTES_LIST_CAKES_SOCKET';
export const UPD_LOTES_LIST_CAKES_SOCKET = 'UPD_LOTES_LIST_CAKES_SOCKET';

export const UPDATE_LOTES_LIST_CAKES_BOOLEAN_SOCKET =
  'UPDATE_LOTES_LIST_CAKES_BOOLEAN_SOCKET';
export const UPD_LOTES_LIST_CAKES_BOOLEAN_SOCKET =
  'UPD_LOTES_LIST_CAKES_BOOLEAN_SOCKET';

export const UPDATE_NEW_RECIPE_SOCKET = 'UPDATE_NEW_RECIPE_SOCKET';
export const UPDATE_RECIPE_SOCKET = 'UPDATE_RECIPE_SOCKET';

export const ADD_NEW_ORDER_TO_WAREHOUSE_SOCKET = 'ADD_NEW_ORDER_TO_WAREHOUSE_SOCKET';
export const NEW_ORDER_TO_WAREHOUSE_SOCKET = 'NEW_ORDER_TO_WAREHOUSE_SOCKET';

export const UPDATE_ORDER_TO_WAREHOUSE_SOCKET = 'UPDATE_ORDER_TO_WAREHOUSE_SOCKET';
export const NEED_UPDATE_ORDER_TO_WAREHOUSE_SOCKET =
  'NEED_UPDATE_ORDER_TO_WAREHOUSE_SOCKET';

export const DELETE_ORDER_TO_WAREHOUSE_SOCKET = 'DELETE_ORDER_TO_WAREHOUSE_SOCKET';

export const NEED_DELETE_ORDER_TO_WAREHOUSE_SOCKET =
  'NEED_DELETE_ORDER_TO_WAREHOUSE_SOCKET';

//PRODUCTION QUALITY
export const ADD_NEW_PRODUCTION_QUALITY_SOCKET = 'ADD_NEW_PRODUCTION_QUALITY_SOCKET';
export const NEW_PRODUCTION_QUALITY_SOCKET = 'NEW_PRODUCTION_QUALITY_SOCKET';

export const UPDATE_PRODUCTION_QUALITY_SOCKET = 'UPDATE_PRODUCTION_QUALITY_SOCKET';
export const NEED_UPDATE_PRODUCTION_QUALITY_SOCKET =
  'NEED_UPDATE_PRODUCTION_QUALITY_SOCKET';

//DIMENSIONS QUALITY
export const ADD_NEW_DIMENSIONS_QUALITY_SOCKET = 'ADD_NEW_DIMENSIONS_QUALITY_SOCKET';
export const NEW_DIMENSIONS_QUALITY_SOCKET = 'NEW_DIMENSIONS_QUALITY_SOCKET';

export const UPDATE_DIMENSIONS_QUALITY_SOCKET = 'UPDATE_DIMENSIONS_QUALITY_SOCKET';
export const UPD_DIMENSIONS_QUALITY_SOCKET = 'UPD_DIMENSIONS_QUALITY_SOCKET';

//COMPRESSIONS QUALITY
export const ADD_NEW_COMPRESSIONS_QUALITY_SOCKET =
  'ADD_NEW_COMPRESSIONS_QUALITY_SOCKET';
export const NEW_COMPRESSIONS_QUALITY_SOCKET = 'NEW_COMPRESSIONS_QUALITY_SOCKET';

export const UPDATE_COMPRESSIONS_QUALITY_SOCKET =
  'UPDATE_COMPRESSIONS_QUALITY_SOCKET';
export const UPD_COMPRESSIONS_QUALITY_SOCKET = 'UPD_COMPRESSIONS_QUALITY_SOCKET';
