const ADD_NEW_PRODUCT_SOCKET = 'ADD_NEW_PRODUCT_SOCKET';
const UPDATE_PRODUCT_SOCKET = 'UPDATE_PRODUCT_SOCKET';

const UPDATE_ROLE_SOCKET = 'UPDATE_ROLE_SOCKET';
const UPDATE_ROLE_ACTIVE_SOCKET = 'UPDATE_ROLE_ACTIVE_SOCKET';

module.exports = {
  ADD_NEW_PRODUCT_SOCKET,
  UPDATE_PRODUCT_SOCKET,
  UPDATE_ROLE_SOCKET,
  UPDATE_ROLE_ACTIVE_SOCKET,
};
