const UPDATE_ROLE_SOCKET = 'UPDATE_ROLE_SOCKET';
const UPDATE_ROLE_ACTIVE_SOCKET = 'UPDATE_ROLE_ACTIVE_SOCKET';

const ADD_NEW_PRODUCT_SOCKET = 'ADD_NEW_PRODUCT_SOCKET';
const UPDATE_PRODUCT_SOCKET = 'UPDATE_PRODUCT_SOCKET';

const ADD_NEW_ORDER_SOCKET = 'ADD_NEW_ORDER_SOCKET';
const ADD_DATASHIP_ORDER_SOCKET = 'ADD_DATASHIP_ORDER_SOCKET';

const UPDATE_PRODUCT_OF_ORDER_SOCKET = 'UPDATE_PRODUCT_OF_ORDER_SOCKET';
const GET_DELETE_PRODUCT_OF_ORDER_SOCKET = 'GET_DELETE_PRODUCT_OF_ORDER_SOCKET';

const GET_DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  'GET_DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET';

const UPDATE_REMAINING_STOCK_SOCKET = 'UPDATE_REMAINING_STOCK_SOCKET';

module.exports = {
  UPDATE_ROLE_SOCKET,
  UPDATE_ROLE_ACTIVE_SOCKET,
  ADD_NEW_PRODUCT_SOCKET,
  UPDATE_PRODUCT_SOCKET,
  ADD_NEW_ORDER_SOCKET,
  ADD_DATASHIP_ORDER_SOCKET,
  UPDATE_PRODUCT_OF_ORDER_SOCKET,
  GET_DELETE_PRODUCT_OF_ORDER_SOCKET,
  GET_DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  UPDATE_REMAINING_STOCK_SOCKET,
};
