const UPDATE_ROLE_SOCKET = "UPDATE_ROLE_SOCKET";
const UPDATE_ROLE_ACTIVE_SOCKET = "UPDATE_ROLE_ACTIVE_SOCKET";

const ADD_NEW_PRODUCT_SOCKET = "ADD_NEW_PRODUCT_SOCKET";
const UPDATE_PRODUCT_SOCKET = "UPDATE_PRODUCT_SOCKET";
const REPAIR_PRODUCT_SOCKET = "REPAIR_PRODUCT_SOCKET";

const ADD_NEW_ALDABARAN_SOCKET = "ADD_NEW_ALDABARAN_SOCKET";

const ADD_NEW_DELIVERY_PRICE_SOCKET = "ADD_NEW_DELIVERY_PRICE_SOCKET";
const ADD_NEW_ORDER_SOCKET = "ADD_NEW_ORDER_SOCKET";
const GET_DELETE_ORDER_SOCKET = "GET_DELETE_ORDER_SOCKET";
const ADD_DATASHIP_ORDER_SOCKET = "ADD_DATASHIP_ORDER_SOCKET";
const ADD_DESCRIPTIOM_ORDER_SOCKET = "ADD_DESCRIPTIOM_ORDER_SOCKET";
const ADD_SECONDARY_CONTACT_ORDER_SOCKET = "ADD_SECONDARY_CONTACT_ORDER_SOCKET";
const DELETE_SECONDARY_CONTACT_ORDER_SOCKET =
  "DELETE_SECONDARY_CONTACT_ORDER_SOCKET";
const UPDATE_STATUS_OF_ORDER_SOCKET = "UPDATE_STATUS_OF_ORDER_SOCKET";

const UPDATE_PRODUCT_OF_ORDER_SOCKET = "UPDATE_PRODUCT_OF_ORDER_SOCKET";
const UPDATE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET =
  "UPDATE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET";
const UPDATE_ANCHOR_PRODUCT_OF_ORDER_SOCKET =
  "UPDATE_ANCHOR_PRODUCT_OF_ORDER_SOCKET";
const UPDATE_TOOL_PRODUCT_OF_ORDER_SOCKET =
  "UPDATE_TOOL_PRODUCT_OF_ORDER_SOCKET";
const UPDATE_REL_MAT_PRODUCT_OF_ORDER_SOCKET =
  "UPDATE_REL_MAT_PRODUCT_OF_ORDER_SOCKET";

const UPDATE_PERSON_IN_CHARGE_OF_ORDER_SOCKET =
  "UPDATE_PERSON_IN_CHARGE_OF_ORDER_SOCKET";

const ADD_NEW_CLIENT_SOCKET = "ADD_NEW_CLIENT_SOCKET";
const UPDATE_CLIENT_SOCKET = "UPDATE_CLIENT_SOCKET";
const NEED_UPD_CONTACT_PRICE_INFO_SOCKET = "NEED_UPD_CONTACT_PRICE_INFO_SOCKET";
const ADD_CLIENTS_LEGAL_ADDRESS_SOCKET = "ADD_CLIENTS_LEGAL_ADDRESS_SOCKET";
const UPDATE_LEGAL_ADDRESS_SOCKET = "UPDATE_LEGAL_ADDRESS_SOCKET";
const ADD_CONTACT_INFO_SOCKET = "ADD_CONTACT_INFO_SOCKET";
const UPDATE_CONTACT_INFO_SOCKET = "UPDATE_CONTACT_INFO_SOCKET";
const ADD_DELIVERY_ADDRESSES_SOCKET = "ADD_DELIVERY_ADDRESSES_SOCKET";
const UPDATE_DELIVERY_ADDRESSES_SOCKET = "UPDATE_DELIVERY_ADDRESSES_SOCKET";

const ADD_NEW_BATCH_OUTSIDE_SOCKET = "ADD_NEW_BATCH_OUTSIDE_SOCKET";
const UPDATE_BATCH_OUTSIDE_SOCKET = "UPDATE_BATCH_OUTSIDE_SOCKET";
const DELETE_BATCH_OUTSIDE_SOCKET = "DELETE_BATCH_OUTSIDE_SOCKET";

const GET_UPDATE_CONTACT_OF_ORDER_SOCKET = "GET_UPDATE_CONTACT_OF_ORDER_SOCKET";
const GET_UPDATE_ADRESS_OF_ORDER_SOCKET = "GET_UPDATE_ADRESS_OF_ORDER_SOCKET";

const GET_DELETE_PRODUCT_OF_ORDER_SOCKET = "GET_DELETE_PRODUCT_OF_ORDER_SOCKET";
const GET_DELETE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET =
  "GET_DELETE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET";
const GET_DELETE_ANCHOR_PRODUCT_OF_ORDER_SOCKET =
  "GET_DELETE_ANCHOR_PRODUCT_OF_ORDER_SOCKET";
const GET_DELETE_TOOL_PRODUCT_OF_ORDER_SOCKET =
  "GET_DELETE_TOOL_PRODUCT_OF_ORDER_SOCKET";
const GET_DELETE_REL_MAT_PRODUCT_OF_ORDER_SOCKET =
  "GET_DELETE_REL_MAT_PRODUCT_OF_ORDER_SOCKET";

const GET_UPDATE_PRODUCT_INFO_OF_ORDER_SOCKET =
  "GET_UPDATE_PRODUCT_INFO_OF_ORDER_SOCKET";

const GET_UPDATE_DRY_MIXED_PRODUCT_INFO_OF_ORDER_SOCKET =
  "GET_UPDATE_DRY_MIXED_PRODUCT_INFO_OF_ORDER_SOCKET";

const GET_UPDATE_ANCHOR_PRODUCT_INFO_OF_ORDER_SOCKET =
  "GET_UPDATE_ANCHOR_PRODUCT_INFO_OF_ORDER_SOCKET";

const GET_UPDATE_TOOL_PRODUCT_INFO_OF_ORDER_SOCKET =
  "GET_UPDATE_TOOL_PRODUCT_INFO_OF_ORDER_SOCKET";

const GET_UPDATE_REL_MAT_PRODUCT_INFO_OF_ORDER_SOCKET =
  "GET_UPDATE_REL_MAT_PRODUCT_INFO_OF_ORDER_SOCKET";

const GET_NEW_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_NEW_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_UPDATE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_UPDATE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_DELETE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_DELETE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_NEW_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_NEW_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_UPDATE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_UPDATE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_DELETE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_DELETE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_NEW_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_NEW_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_UPDATE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_UPDATE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_DELETE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_DELETE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_NEW_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_NEW_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_UPDATE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_UPDATE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_DELETE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_DELETE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_NEW_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_NEW_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_UPDATE_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_UPDATE_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const GET_DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET =
  "GET_DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET";

const ADD_NEW_WAREHOUSE_SOCKET = "ADD_NEW_WAREHOUSE_SOCKET";

const UPDATE_REMAINING_STOCK_SOCKET = "UPDATE_REMAINING_STOCK_SOCKET";
const UPDATE_WAREHOUSE_QUANTITYS_SOCKET = "UPDATE_WAREHOUSE_QUANTITYS_SOCKET";
const UPDATE_DRY_MIXES_QUANTITYS_SOCKET = "UPDATE_DRY_MIXES_QUANTITYS_SOCKET";
const UPDATE_ANCHOR_QUANTITYS_SOCKET = "UPDATE_ANCHOR_QUANTITYS_SOCKET";
const UPDATE_TOOL_QUANTITYS_SOCKET = "UPDATE_TOOL_QUANTITYS_SOCKET";
const UPDATE_REL_MAT_QUANTITYS_SOCKET = "UPDATE_REL_MAT_QUANTITYS_SOCKET";

const ADD_NEW_RAW_MAT_CONSUMPTION_SOCKET = "ADD_NEW_RAW_MAT_CONSUMPTION_SOCKET";
const DELETE_OLD_RAW_MAT_CONSUMPTION_SOCKET =
  "DELETE_OLD_RAW_MAT_CONSUMPTION_SOCKET";
const ADD_NEW_RECIPE_SOCKET = "ADD_NEW_RECIPE_SOCKET";
const DELETE_RECIPE_SOCKET = "DELETE_RECIPE_SOCKET";

const ADD_NEW_FILES_WAREHOUSE_SOCKET = "ADD_NEW_FILES_WAREHOUSE_SOCKET";
const DELETE_FILES_WAREHOUSE_SOCKET = "DELETE_FILES_WAREHOUSE_SOCKET";

const ADD_NEW_FILES_ORDER_SOCKET = "ADD_NEW_FILES_ORDER_SOCKET";
const DELETE_FILES_ORDER_SOCKET = "DELETE_FILES_ORDER_SOCKET";

const SAVE_MATERIAL_PLAN_SOCKET = "SAVE_MATERIAL_PLAN_SOCKET";
const DELETE_MATERIAL_PLAN_SOCKET = "DELETE_MATERIAL_PLAN_SOCKET";

const ADD_NEW_FILES_PRODUCT_SOCKET = "ADD_NEW_FILES_PRODUCT_SOCKET";
const DELETE_FILES_PRODUCT_SOCKET = "DELETE_FILES_PRODUCT_SOCKET";

const ADD_NEW_STOCK_BALANCE_SOCKET = "ADD_NEW_STOCK_BALANCE_SOCKET";

const ADD_NEW_DRY_MIXES_JOURNAL_SOCKET = "ADD_NEW_DRY_MIXES_JOURNAL_SOCKET";
const UPDATE_DRY_MIXES_JOURNAL_SOCKET = "UPDATE_DRY_MIXES_JOURNAL_SOCKET";

const ADD_NEW_RELATED_MATERIALS_JOURNAL_SOCKET =
  "ADD_NEW_RELATED_MATERIALS_JOURNAL_SOCKET";
const UPDATE_RELATED_MATERIALS_JOURNAL_SOCKET =
  "UPDATE_RELATED_MATERIALS_JOURNAL_SOCKET";

const ADD_NEW_ANCHOR_SOCKET = "ADD_NEW_ANCHOR_SOCKET";
const UPDATE_ANCHOR_SOCKET = "UPDATE_ANCHOR_SOCKET";

const ADD_NEW_TOOL_SOCKET = "ADD_NEW_TOOL_SOCKET";
const UPDATE_TOOL_SOCKET = "UPDATE_TOOL_SOCKET";

const ADD_NEW_DRY_MIXES_WAREHOUSE_SOCKET = "ADD_NEW_DRY_MIXES_WAREHOUSE_SOCKET";
const UPDATE_DRY_MIXES_WAREHOUSE_SOCKET = "UPDATE_DRY_MIXES_WAREHOUSE_SOCKET";

const ADD_NEW_RELATED_MATERIALS_WAREHOUSE_SOCKET =
  "ADD_NEW_RELATED_MATERIALS_WAREHOUSE_SOCKET";
const UPDATE_RELATED_MATERIALS_WAREHOUSE_SOCKET =
  "UPDATE_RELATED_MATERIALS_WAREHOUSE_SOCKET";

const ADD_NEW_ANCHORS_WAREHOUSE_SOCKET = "ADD_NEW_ANCHORS_WAREHOUSE_SOCKET";
const UPDATE_ANCHORS_WAREHOUSE_SOCKET = "UPDATE_ANCHORS_WAREHOUSE_SOCKET";

const ADD_NEW_TOOLS_WAREHOUSE_SOCKET = "ADD_NEW_TOOLS_WAREHOUSE_SOCKET";
const UPDATE_TOOLS_WAREHOUSE_SOCKET = "UPDATE_TOOLS_WAREHOUSE_SOCKET";

const UPDATE_RAW_MATERIALS_WAREHOUSE_SOCKET =
  "UPDATE_RAW_MATERIALS_WAREHOUSE_SOCKET";

const ADD_NEW_QUALITY_MANAGEMENT_DATA_SOCKET =
  "ADD_NEW_QUALITY_MANAGEMENT_DATA_SOCKET";
const UPDATE_QUALITY_MANAGEMENT_DATA_SOCKET =
  "UPDATE_QUALITY_MANAGEMENT_DATA_SOCKET";
const DELETE_QUALITY_MANAGEMENT_DATA_SOCKET =
  "DELETE_QUALITY_MANAGEMENT_DATA_SOCKET";

const ADD_NEW_RELATED_MATERIALS_BACKORDER_SOCKET =
  "ADD_NEW_RELATED_MATERIALS_BACKORDER_SOCKET";
const UPDATE_RELATED_MATERIALS_BACKORDER_SOCKET =
  "UPDATE_RELATED_MATERIALS_BACKORDER_SOCKET";

const UPDATE_PRODUCT_CODE_SOCKET = "UPDATE_PRODUCT_CODE_SOCKET";

const ADD_RANDOM_PRODUCTS_OF_ORDER_SOCKET =
  "ADD_RANDOM_PRODUCTS_OF_ORDER_SOCKET";

const GET_UPDATE_AUTOCLAVE_CALENDAR_SOCKET =
  "GET_UPDATE_AUTOCLAVE_CALENDAR_SOCKET";

const ADD_NEW_LIST_OF_ORDERED_PRODUCTION_SOCKET =
  "ADD_NEW_LIST_OF_ORDERED_PRODUCTION_SOCKET";

const GET_UPDATE_LIST_OF_ORDERED_PRODUCTION_SOCKET =
  "GET_UPDATE_LIST_OF_ORDERED_PRODUCTION_SOCKET";

const ADD_NEW_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET =
  "ADD_NEW_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET";

const GET_UPDATE_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET =
  "GET_UPDATE_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET";
const ADD_NEW_WAREHOUSE_SAND_SOCKET = "ADD_NEW_WAREHOUSE_SAND_SOCKET";
const UPDATE_WAREHOUSE_SAND_SOCKET = "UPDATE_WAREHOUSE_SAND_SOCKET";
const DELETE_WAREHOUSE_SAND_SOCKET = "DELETE_WAREHOUSE_SAND_SOCKET";

const ADD_NEW_WAREHOUSE_LIME_SOCKET = "ADD_NEW_WAREHOUSE_LIME_SOCKET";
const UPDATE_WAREHOUSE_LIME_SOCKET = "UPDATE_WAREHOUSE_LIME_SOCKET";
const DELETE_WAREHOUSE_LIME_SOCKET = "DELETE_WAREHOUSE_LIME_SOCKET";

const ADD_NEW_WAREHOUSE_CEMENT_SOCKET = "ADD_NEW_WAREHOUSE_CEMENT_SOCKET";
const UPDATE_WAREHOUSE_CEMENT_SOCKET = "UPDATE_WAREHOUSE_CEMENT_SOCKET";
const DELETE_WAREHOUSE_CEMENT_SOCKET = "DELETE_WAREHOUSE_CEMENT_SOCKET";

const ADD_NEW_WAREHOUSE_GYPSUM_SOCKET = "ADD_NEW_WAREHOUSE_GYPSUM_SOCKET";
const UPDATE_WAREHOUSE_GYPSUM_SOCKET = "UPDATE_WAREHOUSE_GYPSUM_SOCKET";
const DELETE_WAREHOUSE_GYPSUM_SOCKET = "DELETE_WAREHOUSE_GYPSUM_SOCKET";

const ADD_NEW_WAREHOUSE_GYPSUM_STONE_SOCKET =
  "ADD_NEW_WAREHOUSE_GYPSUM_STONE_SOCKET";
const UPDATE_WAREHOUSE_GYPSUM_STONE_SOCKET =
  "UPDATE_WAREHOUSE_GYPSUM_STONE_SOCKET";
const DELETE_WAREHOUSE_GYPSUM_STONE_SOCKET =
  "DELETE_WAREHOUSE_GYPSUM_STONE_SOCKET";

const ADD_NEW_WAREHOUSE_ALUMINUM1_SOCKET = "ADD_NEW_WAREHOUSE_ALUMINUM1_SOCKET";
const UPDATE_WAREHOUSE_ALUMINUM1_SOCKET = "UPDATE_WAREHOUSE_ALUMINUM1_SOCKET";
const DELETE_WAREHOUSE_ALUMINUM1_SOCKET = "DELETE_WAREHOUSE_ALUMINUM1_SOCKET";

const ADD_NEW_WAREHOUSE_ALUMINUM2_SOCKET = "ADD_NEW_WAREHOUSE_ALUMINUM2_SOCKET";
const UPDATE_WAREHOUSE_ALUMINUM2_SOCKET = "UPDATE_WAREHOUSE_ALUMINUM2_SOCKET";
const DELETE_WAREHOUSE_ALUMINUM2_SOCKET = "DELETE_WAREHOUSE_ALUMINUM2_SOCKET";

const ADD_NEW_WAREHOUSE_GRINDING_BALLS_SOCKET =
  "ADD_NEW_WAREHOUSE_GRINDING_BALLS_SOCKET";
const UPDATE_WAREHOUSE_GRINDING_BALLS_SOCKET =
  "UPDATE_WAREHOUSE_GRINDING_BALLS_SOCKET";
const DELETE_WAREHOUSE_GRINDING_BALLS_SOCKET =
  "DELETE_WAREHOUSE_GRINDING_BALLS_SOCKET";

const ADD_NEW_WAREHOUSE_AAC_SOCKET = "ADD_NEW_WAREHOUSE_AAC_SOCKET";
const UPDATE_WAREHOUSE_AAC_SOCKET = "UPDATE_WAREHOUSE_AAC_SOCKET";
const DELETE_WAREHOUSE_AAC_SOCKET = "DELETE_WAREHOUSE_AAC_SOCKET";

const ADD_NEW_LOTES_LIST_SOCKET = "ADD_NEW_LOTES_LIST_SOCKET";

module.exports = {
  ADD_NEW_ALDABARAN_SOCKET,
  NEED_UPD_CONTACT_PRICE_INFO_SOCKET,
  ADD_NEW_DELIVERY_PRICE_SOCKET,
  UPDATE_ROLE_SOCKET,
  UPDATE_ROLE_ACTIVE_SOCKET,
  ADD_NEW_PRODUCT_SOCKET,
  UPDATE_PRODUCT_SOCKET,
  REPAIR_PRODUCT_SOCKET,
  ADD_NEW_ORDER_SOCKET,
  GET_DELETE_ORDER_SOCKET,
  ADD_DATASHIP_ORDER_SOCKET,
  ADD_DESCRIPTIOM_ORDER_SOCKET,
  ADD_SECONDARY_CONTACT_ORDER_SOCKET,
  DELETE_SECONDARY_CONTACT_ORDER_SOCKET,
  UPDATE_STATUS_OF_ORDER_SOCKET,
  UPDATE_PRODUCT_OF_ORDER_SOCKET,
  UPDATE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET,
  UPDATE_ANCHOR_PRODUCT_OF_ORDER_SOCKET,
  UPDATE_TOOL_PRODUCT_OF_ORDER_SOCKET,
  UPDATE_REL_MAT_PRODUCT_OF_ORDER_SOCKET,
  UPDATE_PERSON_IN_CHARGE_OF_ORDER_SOCKET,
  GET_DELETE_PRODUCT_OF_ORDER_SOCKET,
  GET_DELETE_DRY_MIXED_PRODUCT_OF_ORDER_SOCKET,
  GET_DELETE_ANCHOR_PRODUCT_OF_ORDER_SOCKET,
  GET_DELETE_TOOL_PRODUCT_OF_ORDER_SOCKET,
  GET_DELETE_REL_MAT_PRODUCT_OF_ORDER_SOCKET,
  GET_UPDATE_PRODUCT_INFO_OF_ORDER_SOCKET,
  GET_UPDATE_DRY_MIXED_PRODUCT_INFO_OF_ORDER_SOCKET,
  GET_UPDATE_ANCHOR_PRODUCT_INFO_OF_ORDER_SOCKET,
  GET_UPDATE_TOOL_PRODUCT_INFO_OF_ORDER_SOCKET,
  GET_UPDATE_REL_MAT_PRODUCT_INFO_OF_ORDER_SOCKET,
  GET_UPDATE_CONTACT_OF_ORDER_SOCKET,
  GET_UPDATE_ADRESS_OF_ORDER_SOCKET,
  ADD_NEW_CLIENT_SOCKET,
  UPDATE_CLIENT_SOCKET,
  ADD_CLIENTS_LEGAL_ADDRESS_SOCKET,
  UPDATE_LEGAL_ADDRESS_SOCKET,
  ADD_CONTACT_INFO_SOCKET,
  UPDATE_CONTACT_INFO_SOCKET,
  ADD_DELIVERY_ADDRESSES_SOCKET,
  UPDATE_DELIVERY_ADDRESSES_SOCKET,
  ADD_NEW_BATCH_OUTSIDE_SOCKET,
  UPDATE_BATCH_OUTSIDE_SOCKET,
  DELETE_BATCH_OUTSIDE_SOCKET,
  GET_NEW_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_UPDATE_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_DELETE_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_NEW_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_UPDATE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_DELETE_DRY_MIXED_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_NEW_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_UPDATE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_DELETE_ANCHOR_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_NEW_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_UPDATE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_DELETE_TOOL_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_NEW_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_UPDATE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  GET_DELETE_REL_MAT_PRODUCT_FROM_RESERVED_LIST_SOCKET,
  UPDATE_REMAINING_STOCK_SOCKET,
  UPDATE_WAREHOUSE_QUANTITYS_SOCKET,
  UPDATE_DRY_MIXES_QUANTITYS_SOCKET,
  UPDATE_ANCHOR_QUANTITYS_SOCKET,
  UPDATE_TOOL_QUANTITYS_SOCKET,
  UPDATE_REL_MAT_QUANTITYS_SOCKET,
  ADD_NEW_WAREHOUSE_SOCKET,
  ADD_NEW_RAW_MAT_CONSUMPTION_SOCKET,
  DELETE_OLD_RAW_MAT_CONSUMPTION_SOCKET,
  ADD_NEW_RECIPE_SOCKET,
  DELETE_RECIPE_SOCKET,
  ADD_NEW_FILES_WAREHOUSE_SOCKET,
  DELETE_FILES_WAREHOUSE_SOCKET,
  ADD_NEW_FILES_ORDER_SOCKET,
  DELETE_FILES_ORDER_SOCKET,
  SAVE_MATERIAL_PLAN_SOCKET,
  DELETE_MATERIAL_PLAN_SOCKET,
  ADD_NEW_FILES_PRODUCT_SOCKET,
  DELETE_FILES_PRODUCT_SOCKET,
  ADD_NEW_STOCK_BALANCE_SOCKET,
  ADD_NEW_DRY_MIXES_JOURNAL_SOCKET,
  UPDATE_DRY_MIXES_JOURNAL_SOCKET,
  ADD_NEW_RELATED_MATERIALS_JOURNAL_SOCKET,
  UPDATE_RELATED_MATERIALS_JOURNAL_SOCKET,
  ADD_NEW_ANCHOR_SOCKET,
  UPDATE_ANCHOR_SOCKET,
  ADD_NEW_TOOL_SOCKET,
  UPDATE_TOOL_SOCKET,
  ADD_NEW_DRY_MIXES_WAREHOUSE_SOCKET,
  UPDATE_DRY_MIXES_WAREHOUSE_SOCKET,
  ADD_NEW_RELATED_MATERIALS_WAREHOUSE_SOCKET,
  UPDATE_RELATED_MATERIALS_WAREHOUSE_SOCKET,
  ADD_NEW_ANCHORS_WAREHOUSE_SOCKET,
  UPDATE_ANCHORS_WAREHOUSE_SOCKET,
  ADD_NEW_TOOLS_WAREHOUSE_SOCKET,
  UPDATE_TOOLS_WAREHOUSE_SOCKET,
  UPDATE_RAW_MATERIALS_WAREHOUSE_SOCKET,
  ADD_NEW_QUALITY_MANAGEMENT_DATA_SOCKET,
  UPDATE_QUALITY_MANAGEMENT_DATA_SOCKET,
  DELETE_QUALITY_MANAGEMENT_DATA_SOCKET,
  ADD_NEW_RELATED_MATERIALS_BACKORDER_SOCKET,
  UPDATE_RELATED_MATERIALS_BACKORDER_SOCKET,
  UPDATE_PRODUCT_CODE_SOCKET,
  ADD_RANDOM_PRODUCTS_OF_ORDER_SOCKET,
  GET_UPDATE_AUTOCLAVE_CALENDAR_SOCKET,
  ADD_NEW_LIST_OF_ORDERED_PRODUCTION_SOCKET,
  GET_UPDATE_LIST_OF_ORDERED_PRODUCTION_SOCKET,
  ADD_NEW_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET,
  GET_UPDATE_LIST_OF_ORDERED_PRODUCTION_OEM_SOCKET,
  ADD_NEW_WAREHOUSE_SAND_SOCKET,
  UPDATE_WAREHOUSE_SAND_SOCKET,
  DELETE_WAREHOUSE_SAND_SOCKET,
  ADD_NEW_WAREHOUSE_LIME_SOCKET,
  UPDATE_WAREHOUSE_LIME_SOCKET,
  DELETE_WAREHOUSE_LIME_SOCKET,
  ADD_NEW_WAREHOUSE_CEMENT_SOCKET,
  UPDATE_WAREHOUSE_CEMENT_SOCKET,
  DELETE_WAREHOUSE_CEMENT_SOCKET,
  ADD_NEW_WAREHOUSE_GYPSUM_SOCKET,
  UPDATE_WAREHOUSE_GYPSUM_SOCKET,
  DELETE_WAREHOUSE_GYPSUM_SOCKET,
  ADD_NEW_WAREHOUSE_GYPSUM_STONE_SOCKET,
  UPDATE_WAREHOUSE_GYPSUM_STONE_SOCKET,
  DELETE_WAREHOUSE_GYPSUM_STONE_SOCKET,
  ADD_NEW_WAREHOUSE_ALUMINUM1_SOCKET,
  UPDATE_WAREHOUSE_ALUMINUM1_SOCKET,
  DELETE_WAREHOUSE_ALUMINUM1_SOCKET,
  ADD_NEW_WAREHOUSE_ALUMINUM2_SOCKET,
  UPDATE_WAREHOUSE_ALUMINUM2_SOCKET,
  DELETE_WAREHOUSE_ALUMINUM2_SOCKET,
  ADD_NEW_WAREHOUSE_GRINDING_BALLS_SOCKET,
  UPDATE_WAREHOUSE_GRINDING_BALLS_SOCKET,
  DELETE_WAREHOUSE_GRINDING_BALLS_SOCKET,
  ADD_NEW_WAREHOUSE_AAC_SOCKET,
  UPDATE_WAREHOUSE_AAC_SOCKET,
  DELETE_WAREHOUSE_AAC_SOCKET,
  ADD_NEW_LOTES_LIST_SOCKET,
};
