export const GET_ALL_ALDABARAN = 'GET_ALL_ALDABARAN';
export const ALL_ALDABARAN = 'ALL_ALDABARAN';

export const ADD_NEW_ALDABARAN = 'ADD_NEW_ALDABARAN';
export const NEW_ALDABARAN = 'NEW_ALDABARAN';
