export const GET_FULL_BATCH_OUTSIDE = 'GET_FULL_BATCH_OUTSIDE';
export const FULL_BATCH_OUTSIDE = 'FULL_BATCH_OUTSIDE';

export const ADD_NEW_BATCH_OUTSIDE = 'ADD_NEW_BATCH_OUTSIDE';
export const NEW_BATCH_OUTSIDE = 'NEW_BATCH_OUTSIDE';

export const UPDATE_NEW_BATCH_OUTSIDE = 'UPDATE_NEW_BATCH_OUTSIDE';
export const UPDATE_BATCH_OUTSIDE = 'UPDATE_BATCH_OUTSIDE';

export const DELETE_BATCH_OUTSIDE = 'DELETE_BATCH_OUTSIDE';
export const NEED_DELETE_BATCH_OUTSIDE = 'NEED_DELETE_BATCH_OUTSIDE';
