export const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS';
export const ALL_CLIENTS = 'ALL_CLIENTS';

export const ADD_NEW_CLIENT = 'ADD_NEW_CLIENT';
export const NEW_CLIENTS = 'NEW_CLIENTS';

export const ADD_CLIENTS_LEGAL_ADDRESS = 'ADD_CLIENTS_LEGAL_ADDRESS';
export const NEW_LEGAL_ADDRESS = 'NEW_LEGAL_ADDRESS';

export const GET_CLIENTS_LEGAL_ADDRESS = 'GET_CLIENTS_LEGAL_ADDRESS';
export const ONE_LEGAL_ADDRESS = 'ONE_LEGAL_ADDRESS';

export const GET_ALL_DELIVERY_ADDRESSES = 'GET_ALL_DELIVERY_ADDRESSES';
export const ALL_DELIVERY_ADDRESSES = 'ALL_DELIVERY_ADDRESSES';

export const ADD_DELIVERY_ADDRESSES = 'ADD_DELIVERY_ADDRESSES';
export const NEW_DELIVERY_ADDRESSES = 'NEW_DELIVERY_ADDRESSES';

export const GET_ALL_CONTACT_INFO = 'GET_ALL_CONTACT_INFO';
export const ALL_CONTACT_INFO = 'ALL_CONTACT_INFO';

export const ADD_CONTACT_INFO = 'ADD_CONTACT_INFO';
export const NEW_CONTACT_INFO = 'NEW_CONTACT_INFO';

export const NEED_UPDATE_CLIENT = 'NEED_UPDATE_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';

export const NEED_UPDATE_LEGAL_ADDRESS = 'NEED_UPDATE_LEGAL_ADDRESS';
export const UPDATE_LEGAL_ADDRESS = 'UPDATE_LEGAL_ADDRESS';
