export const GET_FULL_FILES_ORDER = 'GET_FULL_FILES_ORDER';
export const FULL_FILES_ORDER = 'FULL_FILES_ORDER';

export const ADD_NEW_FILES_ORDER = 'ADD_NEW_FILES_ORDER';
export const NEW_FILES_ORDER = 'NEW_FILES_ORDER';

export const DELETE_FILES_ORDER = 'DELETE_FILES_ORDER';
export const NEED_DELETE_FILES_ORDER = 'NEED_DELETE_FILES_ORDER';
