export const GET_FULL_FILES_LOTES_LIST = 'GET_FULL_FILES_LOTES_LIST';
export const FULL_FILES_LOTES_LIST = 'FULL_FILES_LOTES_LIST';

export const ADD_NEW_FILES_LOTES_LIST = 'ADD_NEW_FILES_LOTES_LIST';
export const NEW_FILES_LOTES_LIST = 'NEW_FILES_LOTES_LIST';

export const DELETE_FILES_LOTES_LIST = 'DELETE_FILES_LOTES_LIST';
export const NEED_DELETE_FILES_LOTES_LIST = 'NEED_DELETE_FILES_LOTES_LIST';
