export const GET_FULL_FILES_WAREHOUSE = 'GET_FULL_FILES_WAREHOUSE';
export const FULL_FILES_WAREHOUSE = 'FULL_FILES_WAREHOUSE';

export const ADD_NEW_FILES_WAREHOUSE = 'ADD_NEW_FILES_WAREHOUSE';
export const NEW_FILES_WAREHOUSE = 'NEW_FILES_WAREHOUSE';

export const DELETE_FILES_WAREHOUSE = 'DELETE_FILES_WAREHOUSE';
export const NEED_DELETE_FILES_WAREHOUSE = 'NEED_DELETE_FILES_WAREHOUSE';
