export const GET_FULL_FILES_PRODUCT = 'GET_FULL_FILES_PRODUCT';
export const FULL_FILES_PRODUCT = 'FULL_FILES_PRODUCT';

export const ADD_NEW_FILES_PRODUCT = 'ADD_NEW_FILES_PRODUCT';
export const NEW_FILES_PRODUCT = 'NEW_FILES_PRODUCT';

export const DELETE_FILES_PRODUCT = 'DELETE_FILES_PRODUCT';
export const NEED_DELETE_FILES_PRODUCT = 'NEED_DELETE_FILES_PRODUCT';
