export const GET_FULL_LOTES_LIST = 'GET_FULL_LOTES_LIST';
export const FULL_LOTES_LIST = 'FULL_LOTES_LIST';

export const ADD_NEW_LOTES_LIST = 'ADD_NEW_LOTES_LIST';
export const NEW_LOTES_LIST = 'NEW_LOTES_LIST';

export const UPDATE_LOTES_LIST = 'UPDATE_LOTES_LIST';
export const UPD_LOTES_LIST = 'UPD_LOTES_LIST';

export const UPDATE_LOTES_LIST_NOTES = 'UPDATE_LOTES_LIST_NOTES';
export const UPD_LOTES_LIST_NOTES = 'UPD_LOTES_LIST_NOTES';
//-----------------Lotes List Cakes------------------
export const GET_FULL_LOTES_LIST_CAKES = 'GET_FULL_LOTES_LIST_CAKES';
export const FULL_LOTES_LIST_CAKES = 'FULL_LOTES_LIST_CAKES';

export const ADD_NEW_LOTES_LIST_CAKES = 'ADD_NEW_LOTES_LIST_CAKES';
export const NEW_LOTES_LIST_CAKES = 'NEW_LOTES_LIST_CAKES';

export const UPDATE_LOTES_LIST_CAKES = 'UPDATE_LOTES_LIST_CAKES';
export const UPD_LOTES_LIST_CAKES = 'UPD_LOTES_LIST_CAKES';

export const UPDATE_LOTES_LIST_CAKES_BOOLEAN = 'UPDATE_LOTES_LIST_CAKES_BOOLEAN';
export const UPD_LOTES_LIST_CAKES_BOOLEAN = 'UPD_LOTES_LIST_CAKES_BOOLEAN';
