export const GET_ORDERS_LIST = 'GET_ORDERS_LIST';
export const ORDERS_LIST = 'ORDERS_LIST';

export const ADD_NEW_ORDER = 'ADD_NEW_ORDER';
export const NEW_ORDER = 'NEW_ORDER';

export const ADD_DATA_SHIP_ORDER = 'ADD_DATA_SHIP_ORDER';
export const DATA_SHIP_ORDER = 'DATA_SHIP_ORDER';

export const ADD_ORDER_DESCRIPTION = 'ADD_ORDER_DESCRIPTION';
export const ORDER_DESCRIPTION = 'ORDER_DESCRIPTION';

export const ADD_SECONDARY_CONTACT = 'ADD_SECONDARY_CONTACT';
export const SECONDARY_CONTACT = 'SECONDARY_CONTACT';

export const GET_CURRENT_PRODUCTS_OF_ORDER = 'GET_CURRENT_PRODUCTS_OF_ORDER';
export const CURRENT_PRODUCTS_OF_ORDER = 'CURRENT_PRODUCTS_OF_ORDER';

export const GET_PRODUCTS_OF_ORDER = 'GET_PRODUCTS_OF_ORDER';
export const PRODUCTS_OF_ORDER = 'PRODUCTS_OF_ORDER';

export const GET_DRY_MIXED_PRODUCTS_OF_ORDER = 'GET_DRY_MIXED_PRODUCTS_OF_ORDER';
export const DRY_MIXED_PRODUCTS_OF_ORDER = 'DRY_MIXED_PRODUCTS_OF_ORDER';

export const GET_ANCHOR_PRODUCTS_OF_ORDER = 'GET_ANCHOR_PRODUCTS_OF_ORDER';
export const ANCHOR_PRODUCTS_OF_ORDER = 'ANCHOR_PRODUCTS_OF_ORDER';

export const GET_TOOL_PRODUCTS_OF_ORDER = 'GET_TOOL_PRODUCTS_OF_ORDER';
export const TOOL_PRODUCTS_OF_ORDER = 'TOOL_PRODUCTS_OF_ORDER';

export const GET_UPDATE_PRODUCTS_OF_ORDER = 'GET_UPDATE_PRODUCTS_OF_ORDER';
export const UPDATE_PRODUCTS_OF_ORDER = 'UPDATE_PRODUCTS_OF_ORDER';

export const GET_UPDATE_DRY_MIXED_PRODUCTS_OF_ORDER =
  'GET_UPDATE_DRY_MIXED_PRODUCTS_OF_ORDER';
export const UPDATE_DRY_MIXED_PRODUCTS_OF_ORDER =
  'UPDATE_DRY_MIXED_PRODUCTS_OF_ORDER';

export const GET_UPDATE_ANCHOR_PRODUCTS_OF_ORDER =
  'GET_UPDATE_ANCHOR_PRODUCTS_OF_ORDER';
export const UPDATE_ANCHOR_PRODUCTS_OF_ORDER = 'UPDATE_ANCHOR_PRODUCTS_OF_ORDER';

export const GET_UPDATE_TOOL_PRODUCTS_OF_ORDER = 'GET_UPDATE_TOOL_PRODUCTS_OF_ORDER';
export const UPDATE_TOOL_PRODUCTS_OF_ORDER = 'UPDATE_TOOL_PRODUCTS_OF_ORDER';

export const GET_UPDATE_PRODUCT_INFO_OF_ORDER = 'GET_UPDATE_PRODUCT_INFO_OF_ORDER';
export const UPDATE_PRODUCT_INFO_OF_ORDER = 'UPDATE_PRODUCT_INFO_OF_ORDER';

export const GET_DELETE_PRODUCT_OF_ORDER = 'GET_DELETE_PRODUCT_OF_ORDER';
export const DELETE_PRODUCT_OF_ORDER = 'DELETE_PRODUCT_OF_ORDER';

export const GET_DELETE_DRY_MIXED_OF_ORDER = 'GET_DELETE_DRY_MIXED_OF_ORDER';
export const DELETE_DRY_MIXED_OF_ORDER = 'DELETE_DRY_MIXED_OF_ORDER';

export const GET_DELETE_ANCHOR_OF_ORDER = 'GET_DELETE_ANCHOR_OF_ORDER';
export const DELETE_ANCHOR_OF_ORDER = 'DELETE_ANCHOR_OF_ORDER';

export const GET_DELETE_TOOL_OF_ORDER = 'GET_DELETE_TOOL_OF_ORDER';
export const DELETE_TOOL_OF_ORDER = 'DELETE_TOOL_OF_ORDER';

export const GET_DELETE_ORDER = 'GET_DELETE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';

export const UPDATE_CONTACT_OF_ORDER = 'UPDATE_CONTACT_OF_ORDER';
export const NEW_CONTACT_OF_ORDER = 'NEW_CONTACT_OF_ORDER';

export const UPDATE_DELIVERY_OF_ORDER = 'UPDATE_DELIVERY_OF_ORDER';
export const NEW_DELIVERY_OF_ORDER = 'NEW_DELIVERY_OF_ORDER';

export const UPDATE_STATUS_OF_ORDER = 'UPDATE_STATUS_OF_ORDER';
export const STATUS_OF_ORDER = 'STATUS_OF_ORDER';

export const UPDATE_PERSON_IN_CHARGE_OF_ORDER = 'UPDATE_PERSON_IN_CHARGE_OF_ORDER';
export const PERSON_IN_CHARGE_OF_ORDER = 'PERSON_IN_CHARGE_OF_ORDER';

export const CLEAR_ACCOUTING_DATA_LIST = 'CLEAR_ACCOUTING_DATA_LIST';
export const ADD_ACCOUTING_DATA_LIST = 'ADD_ACCOUTING_DATA_LIST';
export const UPD_ACCOUTING_DATA_LIST = 'UPD_ACCOUTING_DATA_LIST';
export const DELETE_ACCOUTING_DATA_LIST = 'DELETE_ACCOUTING_DATA_LIST';
