export const GET_ORDERS_LIST = 'GET_ORDERS_LIST';
export const ORDERS_LIST = 'ORDERS_LIST';

export const ADD_NEW_ORDER = 'ADD_NEW_ORDER';
export const NEW_ORDER = 'NEW_ORDER';

export const GET_PRODUCTS_OF_ORDER = 'GET_PRODUCTS_OF_ORDER';
export const PRODUCTS_OF_ORDER = 'PRODUCTS_OF_ORDER';

export const GET_UPDATE_PRODUCTS_OF_ORDER = 'GET_UPDATE_PRODUCTS_OF_ORDER';
export const UPDATE_PRODUCTS_OF_ORDER = 'UPDATE_PRODUCTS_OF_ORDER';

export const GET_DELETE_PRODUCT_OF_ORDER = 'GET_DELETE_PRODUCT_OF_ORDER';
export const DELETE_PRODUCT_OF_ORDER = 'DELETE_PRODUCT_OF_ORDER';

export const GET_DELETE_ORDER = 'GET_DELETE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
