export const GET_ORDERS_LIST = 'GET_ORDERS_LIST';
export const ORDERS_LIST = 'ORDERS_LIST';

export const ADD_NEW_ORDER = 'ADD_NEW_ORDER';
export const NEW_ORDER = 'NEW_ORDER';

export const ADD_DATA_SHIP_ORDER = 'ADD_DATA_SHIP_ORDER';
export const DATA_SHIP_ORDER = 'DATA_SHIP_ORDER';

export const GET_PRODUCTS_OF_ORDER = 'GET_PRODUCTS_OF_ORDER';
export const PRODUCTS_OF_ORDER = 'PRODUCTS_OF_ORDER';

export const GET_UPDATE_PRODUCT_INFO_OF_ORDER = 'GET_UPDATE_PRODUCT_INFO_OF_ORDER';
export const UPDATE_PRODUCT_INFO_OF_ORDER = 'UPDATE_PRODUCT_INFO_OF_ORDER';

export const GET_UPDATE_PRODUCTS_OF_ORDER = 'GET_UPDATE_PRODUCTS_OF_ORDER';
export const UPDATE_PRODUCTS_OF_ORDER = 'UPDATE_PRODUCTS_OF_ORDER';

export const GET_DELETE_PRODUCT_OF_ORDER = 'GET_DELETE_PRODUCT_OF_ORDER';
export const DELETE_PRODUCT_OF_ORDER = 'DELETE_PRODUCT_OF_ORDER';

export const GET_DELETE_ORDER = 'GET_DELETE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';

export const UPDATE_CONTACT_OF_ORDER = 'UPDATE_CONTACT_OF_ORDER';
export const NEW_CONTACT_OF_ORDER = 'NEW_CONTACT_OF_ORDER';

export const UPDATE_DELIVERY_OF_ORDER = 'UPDATE_DELIVERY_OF_ORDER';
export const NEW_DELIVERY_OF_ORDER = 'NEW_DELIVERY_OF_ORDER';

export const UPDATE_STATUS_OF_ORDER = 'UPDATE_STATUS_OF_ORDER';
export const STATUS_OF_ORDER = 'STATUS_OF_ORDER';
