export const GET_FULL_ORDER_TO_WAREHOUSE = 'GET_FULL_ORDER_TO_WAREHOUSE';
export const FULL_ORDER_TO_WAREHOUSE = 'FULL_ORDER_TO_WAREHOUSE';

export const ADD_NEW_ORDER_TO_WAREHOUSE = 'ADD_NEW_ORDER_TO_WAREHOUSE';
export const NEW_ORDER_TO_WAREHOUSE = 'NEW_ORDER_TO_WAREHOUSE';

export const UPDATE_NEW_ORDER_TO_WAREHOUSE = 'UPDATE_NEW_ORDER_TO_WAREHOUSE';
export const UPDATE_ORDER_TO_WAREHOUSE = 'UPDATE_ORDER_TO_WAREHOUSE';

export const DELETE_ORDER_TO_WAREHOUSE = 'DELETE_ORDER_TO_WAREHOUSE';
export const NEED_DELETE_ORDER_TO_WAREHOUSE = 'NEED_DELETE_ORDER_TO_WAREHOUSE';
