export const GET_FULL_DRY_MIXES_JOURNAL = 'GET_FULL_DRY_MIXES_JOURNAL';
export const FULL_DRY_MIXES_JOURNAL = 'FULL_DRY_MIXES_JOURNAL';

export const ADD_NEW_DRY_MIXES_JOURNAL = 'ADD_NEW_DRY_MIXES_JOURNAL';
export const NEW_DRY_MIXES_JOURNAL = 'NEW_DRY_MIXES_JOURNAL';

export const UPDATE_NEW_DRY_MIXES_JOURNAL = 'UPDATE_NEW_DRY_MIXES_JOURNAL';
export const UPDATE_DRY_MIXES_JOURNAL = 'UPDATE_DRY_MIXES_JOURNAL';

export const GET_FULL_RELATED_MATERIALS_JOURNAL =
  'GET_FULL_RELATED_MATERIALS_JOURNAL';
export const FULL_RELATED_MATERIALS_JOURNAL = 'FULL_RELATED_MATERIALS_JOURNAL';

export const ADD_NEW_RELATED_MATERIALS_JOURNAL = 'ADD_NEW_RELATED_MATERIALS_JOURNAL';
export const NEW_RELATED_MATERIALS_JOURNAL = 'NEW_RELATED_MATERIALS_JOURNAL';

export const UPDATE_NEW_RELATED_MATERIALS_JOURNAL =
  'UPDATE_NEW_RELATED_MATERIALS_JOURNAL';
export const UPDATE_RELATED_MATERIALS_JOURNAL = 'UPDATE_RELATED_MATERIALS_JOURNAL';
