export const GET_ALL_PRODUCTION_BATCH_LOGS = 'GET_ALL_PRODUCTION_BATCH_LOGS';
export const ALL_PRODUCTION_BATCH_LOGS = 'ALL_PRODUCTION_BATCH_LOGS';

export const ADD_NEW_PRODUCTION_BATCH_LOG = 'ADD_NEW_PRODUCTION_BATCH_LOG';
export const NEW_PRODUCTION_BATCH_LOG = 'NEW_PRODUCTION_BATCH_LOG';

export const NEED_UPDATE_PRODUCTION_BATCH_LOG = 'NEED_UPDATE_PRODUCTION_BATCH_LOG';
export const UPDATE_PRODUCTION_BATCH_LOG = 'UPDATE_PRODUCTION_BATCH_LOG';

/////////////////////////BUTCH DESIGNER////////////////////////

export const UPDATE_BATCH_BUTTON_STATUS = 'UPDATE_BATCH_BUTTON_STATUS';
export const UPDATE_BATCH_STATE = 'UPDATE_BATCH_STATE';
export const ADD_BATCH_STATE = 'ADD_BATCH_STATE';
