//PRODUCTION QUALITY
export const GET_ALL_PRODUCTION_QUALITY = 'GET_ALL_PRODUCTION_QUALITY';
export const ALL_PRODUCTION_QUALITY = 'ALL_PRODUCTION_QUALITY';

export const ADD_NEW_PRODUCTION_QUALITY = 'ADD_NEW_PRODUCTION_QUALITY';
export const NEW_PRODUCTION_QUALITY = 'NEW_PRODUCTION_QUALITY';

//DIMENSION QUALITY
export const GET_ALL_DIMENSIONS_QUALITY = 'GET_ALL_DIMENSIONS_QUALITY';
export const ALL_DIMENSIONS_QUALITY = 'ALL_DIMENSIONS_QUALITY';

export const ADD_NEW_DIMENSIONS_QUALITY = 'ADD_NEW_DIMENSIONS_QUALITY';
export const NEW_DIMENSIONS_QUALITY = 'NEW_DIMENSIONS_QUALITY';

export const UPDATE_DIMENSIONS_QUALITY = 'UPDATE_DIMENSIONS_QUALITY';
export const UPD_DIMENSIONS_QUALITY = 'UPD_DIMENSIONS_QUALITY';

//COMPRESSIONS QUALITY
export const GET_ALL_COMPRESSIONS_QUALITY = 'GET_ALL_COMPRESSIONS_QUALITY';
export const ALL_COMPRESSIONS_QUALITY = 'ALL_COMPRESSIONS_QUALITY';

export const ADD_NEW_COMPRESSIONS_QUALITY = 'ADD_NEW_COMPRESSIONS_QUALITY';
export const NEW_COMPRESSIONS_QUALITY = 'NEW_COMPRESSIONS_QUALITY';

export const UPDATE_COMPRESSIONS_QUALITY = 'UPDATE_COMPRESSIONS_QUALITY';
export const UPD_COMPRESSIONS_QUALITY = 'UPD_COMPRESSIONS_QUALITY';
