export const GET_ALL_PRODUCTION_QUALITY = 'GET_ALL_PRODUCTION_QUALITY';
export const ALL_PRODUCTION_QUALITY = 'ALL_PRODUCTION_QUALITY';

export const ADD_NEW_PRODUCTION_QUALITY = 'ADD_NEW_PRODUCTION_QUALITY';
export const NEW_PRODUCTION_QUALITY = 'NEW_PRODUCTION_QUALITY';

