export const GET_FULL_DRY_MIXES_WAREHOUSE = 'GET_FULL_DRY_MIXES_WAREHOUSE';
export const FULL_DRY_MIXES_WAREHOUSE = 'FULL_DRY_MIXES_WAREHOUSE';

export const ADD_NEW_DRY_MIXES_WAREHOUSE = 'ADD_NEW_DRY_MIXES_WAREHOUSE';
export const NEW_DRY_MIXES_WAREHOUSE = 'NEW_DRY_MIXES_WAREHOUSE';

export const UPDATE_NEW_DRY_MIXES_WAREHOUSE = 'UPDATE_NEW_DRY_MIXES_WAREHOUSE';
export const UPDATE_DRY_MIXES_WAREHOUSE = 'UPDATE_DRY_MIXES_WAREHOUSE';

export const GET_FULL_RELATED_MATERIALS_WAREHOUSE =
  'GET_FULL_RELATED_MATERIALS_WAREHOUSE';
export const FULL_RELATED_MATERIALS_WAREHOUSE = 'FULL_RELATED_MATERIALS_WAREHOUSE';

export const ADD_NEW_RELATED_MATERIALS_WAREHOUSE =
  'ADD_NEW_RELATED_MATERIALS_WAREHOUSE';
export const NEW_RELATED_MATERIALS_WAREHOUSE = 'NEW_RELATED_MATERIALS_WAREHOUSE';

export const UPDATE_NEW_RELATED_MATERIALS_WAREHOUSE =
  'UPDATE_NEW_RELATED_MATERIALS_WAREHOUSE';
export const UPDATE_RELATED_MATERIALS_WAREHOUSE =
  'UPDATE_RELATED_MATERIALS_WAREHOUSE';

export const GET_FULL_ANCHORS_WAREHOUSE = 'GET_FULL_ANCHORS_WAREHOUSE';
export const FULL_ANCHORS_WAREHOUSE = 'FULL_ANCHORS_WAREHOUSE';

export const ADD_NEW_ANCHORS_WAREHOUSE = 'ADD_NEW_ANCHORS_WAREHOUSE';
export const NEW_ANCHORS_WAREHOUSE = 'NEW_ANCHORS_WAREHOUSE';

export const UPDATE_NEW_ANCHORS_WAREHOUSE = 'UPDATE_NEW_ANCHORS_WAREHOUSE';
export const UPDATE_ANCHORS_WAREHOUSE = 'UPDATE_ANCHORS_WAREHOUSE';

export const GET_FULL_TOOLS_WAREHOUSE = 'GET_FULL_TOOLS_WAREHOUSE';
export const FULL_TOOLS_WAREHOUSE = 'FULL_TOOLS_WAREHOUSE';

export const ADD_NEW_TOOLS_WAREHOUSE = 'ADD_NEW_TOOLS_WAREHOUSE';
export const NEW_TOOLS_WAREHOUSE = 'NEW_TOOLS_WAREHOUSE';

export const UPDATE_NEW_TOOLS_WAREHOUSE = 'UPDATE_NEW_TOOLS_WAREHOUSE';
export const UPDATE_TOOLS_WAREHOUSE = 'UPDATE_TOOLS_WAREHOUSE';
