export const GET_FULL_DRY_MIXES_JOURNAL = 'GET_FULL_DRY_MIXES_JOURNAL';
export const FULL_DRY_MIXES_JOURNAL = 'FULL_DRY_MIXES_JOURNAL';

export const ADD_NEW_DRY_MIXES_JOURNAL = 'ADD_NEW_DRY_MIXES_JOURNAL';
export const NEW_DRY_MIXES_JOURNAL = 'NEW_DRY_MIXES_JOURNAL';

export const UPDATE_NEW_DRY_MIXES_JOURNAL = 'UPDATE_NEW_DRY_MIXES_JOURNAL';
export const UPDATE_DRY_MIXES_JOURNAL = 'UPDATE_DRY_MIXES_JOURNAL';

export const GET_FULL_RELATED_MATERIALS_JOURNAL =
  'GET_FULL_RELATED_MATERIALS_JOURNAL';
export const FULL_RELATED_MATERIALS_JOURNAL = 'FULL_RELATED_MATERIALS_JOURNAL';

export const ADD_NEW_RELATED_MATERIALS_JOURNAL = 'ADD_NEW_RELATED_MATERIALS_JOURNAL';
export const NEW_RELATED_MATERIALS_JOURNAL = 'NEW_RELATED_MATERIALS_JOURNAL';

export const UPDATE_NEW_RELATED_MATERIALS_JOURNAL =
  'UPDATE_NEW_RELATED_MATERIALS_JOURNAL';
export const UPDATE_RELATED_MATERIALS_JOURNAL = 'UPDATE_RELATED_MATERIALS_JOURNAL';

export const GET_FULL_ANCHOR = 'GET_FULL_ANCHOR';
export const FULL_ANCHOR = 'FULL_ANCHOR';

export const ADD_NEW_ANCHOR = 'ADD_NEW_ANCHOR';
export const NEW_ANCHOR = 'NEW_ANCHOR';

export const UPDATE_NEW_ANCHOR = 'UPDATE_NEW_ANCHOR';
export const UPDATE_ANCHOR = 'UPDATE_ANCHOR';

export const GET_FULL_TOOL = 'GET_FULL_TOOL';
export const FULL_TOOL = 'FULL_TOOL';

export const ADD_NEW_TOOL = 'ADD_NEW_TOOL';
export const NEW_TOOL = 'NEW_TOOL';

export const UPDATE_NEW_TOOL = 'UPDATE_NEW_TOOL';
export const UPDATE_TOOL = 'UPDATE_TOOL';

export const GET_FULL_PRODUCT_CODE = 'GET_FULL_PRODUCT_CODE';
export const FULL_PRODUCT_CODE = 'FULL_PRODUCT_CODE';

export const UPDATE_NEW_PRODUCT_CODE = 'UPDATE_NEW_PRODUCT_CODE';
export const UPDATE_PRODUCT_CODE = 'UPDATE_PRODUCT_CODE';
