export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const ALL_PRODUCTS = 'ALL_PRODUCTS';

export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const NEW_PRODUCT = 'NEW_PRODUCT';

export const NEED_UPDATE_PRODUCT = 'NEED_UPDATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const REPAIR_PRODUCT = 'REPAIR_PRODUCT';
export const REP_PRODUCT = 'REP_PRODUCT';

export const FIX_PRODUCT_ARTICLES = 'FIX_PRODUCT_ARTICLES';

export const FIX_PRODUCT_DESCRIPTIONS = 'FIX_PRODUCT_DESCRIPTIONS';

export const CHANGE_PRODUCT_PRICES = 'CHANGE_PRODUCT_PRICES';
