export const GET_FULL_QUALITY_MANAGEMENT_DATA = 'GET_FULL_QUALITY_MANAGEMENT_DATA';
export const FULL_QUALITY_MANAGEMENT_DATA = 'FULL_QUALITY_MANAGEMENT_DATA';

export const ADD_NEW_QUALITY_MANAGEMENT_DATA = 'ADD_NEW_QUALITY_MANAGEMENT_DATA';
export const NEW_QUALITY_MANAGEMENT_DATA = 'NEW_QUALITY_MANAGEMENT_DATA';

export const UPDATE_NEW_QUALITY_MANAGEMENT_DATA =
  'UPDATE_NEW_QUALITY_MANAGEMENT_DATA';
export const UPDATE_QUALITY_MANAGEMENT_DATA = 'UPDATE_QUALITY_MANAGEMENT_DATA';

export const DELETE_QUALITY_MANAGEMENT_DATA = 'DELETE_QUALITY_MANAGEMENT_DATA';
export const NEED_DELETE_QUALITY_MANAGEMENT_DATA =
  'NEED_DELETE_QUALITY_MANAGEMENT_DATA';
