export const GET_FULL_RECIPE = 'GET_FULL_RECIPE';
export const FULL_RECIPE = 'FULL_RECIPE';

export const ADD_NEW_RECIPE = 'ADD_NEW_RECIPE';
export const NEW_RECIPE = 'NEW_RECIPE';

export const SAVE_MATERIAL_PLAN = 'SAVE_MATERIAL_PLAN';

