export const GET_FULL_RECIPE = 'GET_FULL_RECIPE';
export const FULL_RECIPE = 'FULL_RECIPE';

export const ADD_NEW_RECIPE = 'ADD_NEW_RECIPE';
export const NEW_RECIPE = 'NEW_RECIPE';

export const SAVE_MATERIAL_PLAN = 'SAVE_MATERIAL_PLAN';
export const GET_RECIPE_ORDERS_DATA = 'GET_RECIPE_ORDERS_DATA';
export const RECIPE_ORDERS_DATA = 'RECIPE_ORDERS_DATA';

export const DELETE_RECIPE = 'DELETE_RECIPE';
export const NEED_DELETE_RECIPE = 'NEED_DELETE_RECIPE';
