export const GET_FULL_RELATED_MATERIALS_BACKORDER =
  'GET_FULL_RELATED_MATERIALS_BACKORDER';
export const FULL_RELATED_MATERIALS_BACKORDER = 'FULL_RELATED_MATERIALS_BACKORDER';

export const ADD_NEW_RELATED_MATERIALS_BACKORDER =
  'ADD_NEW_RELATED_MATERIALS_BACKORDER';
export const NEW_RELATED_MATERIALS_BACKORDER = 'NEW_RELATED_MATERIALS_BACKORDER';

export const UPDATE_NEW_RELATED_MATERIALS_BACKORDER =
  'UPDATE_NEW_RELATED_MATERIALS_BACKORDER';
export const UPDATE_RELATED_MATERIALS_BACKORDER =
  'UPDATE_RELATED_MATERIALS_BACKORDER';
