export const GET_ALL_ROLES = 'GET_ALL_ROLES';
export const ALL_ROLES = 'ALL_ROLES';

export const GET_ALL_PAGES = 'GET_ALL_PAGES';
export const ALL_PAGES = 'ALL_PAGES';

export const NEED_UPDATE_ROLE_ACTIVE = 'NEED_UPDATE_ROLE_ACTIVE';
export const UPDATE_ROLE_ACTIVE = 'UPDATE_ROLE_ACTIVE';

export const NEED_UPDATE_ROLE = 'NEED_UPDATE_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
