export const GET_ALL_STOCK_BALANCE = 'GET_ALL_STOCK_BALANCE';
export const ADD_NEW_STOCK_BALANCE = 'ADD_NEW_STOCK_BALANCE';

export const ALL_STOCK_BALANCE = 'ALL_STOCK_BALANCE';
export const NEW_STOCK_BALANCE = 'NEW_STOCK_BALANCE';
