export const GET_ALL_USERS_INFO = 'GET_ALL_USERS_INFO';
export const ALL_USERS_INFO = 'ALL_USERS_INFO';

export const ADD_NEW_USERS_INFO = 'ADD_NEW_USERS_INFO';
export const NEW_USERS_INFO = 'NEW_USERS_INFO';

export const NEED_UPDATE_USERS_INFO = 'NEED_UPDATE_USERS_INFO';
export const UPDATE_USERS_INFO = 'UPDATE_USERS_INFO';

export const GET_ALL_USERS_MAIN_INFO = 'GET_ALL_USERS_MAIN_INFO';
export const ALL_USERS_MAIN_INFO = 'ALL_USERS_MAIN_INFO';

export const ADD_NEW_USERS_MAIN_INFO = 'ADD_NEW_USERS_MAIN_INFO';
export const NEW_USERS_MAIN_INFO = 'NEW_USERS_MAIN_INFO';

export const NEED_UPDATE_USERS_MAIN_INFO = 'NEED_UPDATE_USERS_MAIN_INFO';
export const UPDATE_USERS_MAIN_INFO = 'UPDATE_USERS_MAIN_INFO';
