export const GET_FULL_WAREHOUSE_SAND = 'GET_FULL_WAREHOUSE_SAND';
export const FULL_WAREHOUSE_SAND = 'FULL_WAREHOUSE_SAND';

export const ADD_NEW_WAREHOUSE_SAND = 'ADD_NEW_WAREHOUSE_SAND';
export const NEW_WAREHOUSE_SAND = 'NEW_WAREHOUSE_SAND';

export const UPDATE_NEW_WAREHOUSE_SAND = 'UPDATE_NEW_WAREHOUSE_SAND';
export const UPDATE_WAREHOUSE_SAND = 'UPDATE_WAREHOUSE_SAND';

export const DELETE_WAREHOUSE_SAND = 'DELETE_WAREHOUSE_SAND';
export const NEED_DELETE_WAREHOUSE_SAND = 'NEED_DELETE_WAREHOUSE_SAND';

export const GET_FULL_WAREHOUSE_LIME = 'GET_FULL_WAREHOUSE_LIME';
export const FULL_WAREHOUSE_LIME = 'FULL_WAREHOUSE_LIME';

export const ADD_NEW_WAREHOUSE_LIME = 'ADD_NEW_WAREHOUSE_LIME';
export const NEW_WAREHOUSE_LIME = 'NEW_WAREHOUSE_LIME';

export const UPDATE_NEW_WAREHOUSE_LIME = 'UPDATE_NEW_WAREHOUSE_LIME';
export const UPDATE_WAREHOUSE_LIME = 'UPDATE_WAREHOUSE_LIME';

export const DELETE_WAREHOUSE_LIME = 'DELETE_WAREHOUSE_LIME';
export const NEED_DELETE_WAREHOUSE_LIME = 'NEED_DELETE_WAREHOUSE_LIME';

export const GET_FULL_WAREHOUSE_CEMENT = 'GET_FULL_WAREHOUSE_CEMENT';
export const FULL_WAREHOUSE_CEMENT = 'FULL_WAREHOUSE_CEMENT';

export const ADD_NEW_WAREHOUSE_CEMENT = 'ADD_NEW_WAREHOUSE_CEMENT';
export const NEW_WAREHOUSE_CEMENT = 'NEW_WAREHOUSE_CEMENT';

export const UPDATE_NEW_WAREHOUSE_CEMENT = 'UPDATE_NEW_WAREHOUSE_CEMENT';
export const UPDATE_WAREHOUSE_CEMENT = 'UPDATE_WAREHOUSE_CEMENT';

export const DELETE_WAREHOUSE_CEMENT = 'DELETE_WAREHOUSE_CEMENT';
export const NEED_DELETE_WAREHOUSE_CEMENT = 'NEED_DELETE_WAREHOUSE_CEMENT';

export const GET_FULL_WAREHOUSE_GYPSUM = 'GET_FULL_WAREHOUSE_GYPSUM';
export const FULL_WAREHOUSE_GYPSUM = 'FULL_WAREHOUSE_GYPSUM';

export const ADD_NEW_WAREHOUSE_GYPSUM = 'ADD_NEW_WAREHOUSE_GYPSUM';
export const NEW_WAREHOUSE_GYPSUM = 'NEW_WAREHOUSE_GYPSUM';

export const UPDATE_NEW_WAREHOUSE_GYPSUM = 'UPDATE_NEW_WAREHOUSE_GYPSUM';
export const UPDATE_WAREHOUSE_GYPSUM = 'UPDATE_WAREHOUSE_GYPSUM';

export const DELETE_WAREHOUSE_GYPSUM = 'DELETE_WAREHOUSE_GYPSUM';
export const NEED_DELETE_WAREHOUSE_GYPSUM = 'NEED_DELETE_WAREHOUSE_GYPSUM';

export const GET_FULL_WAREHOUSE_GYPSUM_STONE =
  'GET_FULL_WAREHOUSE_GYPSUM_STONE';
export const FULL_WAREHOUSE_GYPSUM_STONE = 'FULL_WAREHOUSE_GYPSUM_STONE';

export const ADD_NEW_WAREHOUSE_GYPSUM_STONE = 'ADD_NEW_WAREHOUSE_GYPSUM_STONE';
export const NEW_WAREHOUSE_GYPSUM_STONE = 'NEW_WAREHOUSE_GYPSUM_STONE';

export const UPDATE_NEW_WAREHOUSE_GYPSUM_STONE =
  'UPDATE_NEW_WAREHOUSE_GYPSUM_STONE';
export const UPDATE_WAREHOUSE_GYPSUM_STONE = 'UPDATE_WAREHOUSE_GYPSUM_STONE';

export const DELETE_WAREHOUSE_GYPSUM_STONE = 'DELETE_WAREHOUSE_GYPSUM_STONE';
export const NEED_DELETE_WAREHOUSE_GYPSUM_STONE =
  'NEED_DELETE_WAREHOUSE_GYPSUM_STONE';

export const GET_FULL_WAREHOUSE_ALUMINUM1 = 'GET_FULL_WAREHOUSE_ALUMINUM1';
export const FULL_WAREHOUSE_ALUMINUM1 = 'FULL_WAREHOUSE_ALUMINUM1';

export const ADD_NEW_WAREHOUSE_ALUMINUM1 = 'ADD_NEW_WAREHOUSE_ALUMINUM1';
export const NEW_WAREHOUSE_ALUMINUM1 = 'NEW_WAREHOUSE_ALUMINUM1';

export const UPDATE_NEW_WAREHOUSE_ALUMINUM1 = 'UPDATE_NEW_WAREHOUSE_ALUMINUM1';
export const UPDATE_WAREHOUSE_ALUMINUM1 = 'UPDATE_WAREHOUSE_ALUMINUM1';

export const DELETE_WAREHOUSE_ALUMINUM1 = 'DELETE_WAREHOUSE_ALUMINUM1';
export const NEED_DELETE_WAREHOUSE_ALUMINUM1 =
  'NEED_DELETE_WAREHOUSE_ALUMINUM1';

export const GET_FULL_WAREHOUSE_ALUMINUM2 = 'GET_FULL_WAREHOUSE_ALUMINUM2';
export const FULL_WAREHOUSE_ALUMINUM2 = 'FULL_WAREHOUSE_ALUMINUM2';

export const ADD_NEW_WAREHOUSE_ALUMINUM2 = 'ADD_NEW_WAREHOUSE_ALUMINUM2';
export const NEW_WAREHOUSE_ALUMINUM2 = 'NEW_WAREHOUSE_ALUMINUM2';

export const UPDATE_NEW_WAREHOUSE_ALUMINUM2 = 'UPDATE_NEW_WAREHOUSE_ALUMINUM2';
export const UPDATE_WAREHOUSE_ALUMINUM2 = 'UPDATE_WAREHOUSE_ALUMINUM2';

export const DELETE_WAREHOUSE_ALUMINUM2 = 'DELETE_WAREHOUSE_ALUMINUM2';
export const NEED_DELETE_WAREHOUSE_ALUMINUM2 =
  'NEED_DELETE_WAREHOUSE_ALUMINUM2';

export const GET_FULL_WAREHOUSE_GRINDING_BALLS =
  'GET_FULL_WAREHOUSE_GRINDING_BALLS';
export const FULL_WAREHOUSE_GRINDING_BALLS = 'FULL_WAREHOUSE_GRINDING_BALLS';

export const ADD_NEW_WAREHOUSE_GRINDING_BALLS =
  'ADD_NEW_WAREHOUSE_GRINDING_BALLS';
export const NEW_WAREHOUSE_GRINDING_BALLS = 'NEW_WAREHOUSE_GRINDING_BALLS';

export const UPDATE_NEW_WAREHOUSE_GRINDING_BALLS =
  'UPDATE_NEW_WAREHOUSE_GRINDING_BALLS';
export const UPDATE_WAREHOUSE_GRINDING_BALLS =
  'UPDATE_WAREHOUSE_GRINDING_BALLS';

export const DELETE_WAREHOUSE_GRINDING_BALLS =
  'DELETE_WAREHOUSE_GRINDING_BALLS';
export const NEED_DELETE_WAREHOUSE_GRINDING_BALLS =
  'NEED_DELETE_WAREHOUSE_GRINDING_BALLS';

export const GET_FULL_WAREHOUSE_AAC = 'GET_FULL_WAREHOUSE_AAC';
export const FULL_WAREHOUSE_AAC = 'FULL_WAREHOUSE_AAC';

export const ADD_NEW_WAREHOUSE_AAC = 'ADD_NEW_WAREHOUSE_AAC';
export const NEW_WAREHOUSE_AAC = 'NEW_WAREHOUSE_AAC';

export const UPDATE_NEW_WAREHOUSE_AAC = 'UPDATE_NEW_WAREHOUSE_AAC';
export const UPDATE_WAREHOUSE_AAC = 'UPDATE_WAREHOUSE_AAC';

export const DELETE_WAREHOUSE_AAC = 'DELETE_WAREHOUSE_AAC';
export const NEED_DELETE_WAREHOUSE_AAC = 'NEED_DELETE_WAREHOUSE_AAC';

export const GET_FULL_WAREHOUSE_SAND_SLURRY = 'GET_FULL_WAREHOUSE_SAND_SLURRY';
export const FULL_WAREHOUSE_SAND_SLURRY = 'FULL_WAREHOUSE_SAND_SLURRY';

export const ADD_NEW_WAREHOUSE_SAND_SLURRY = 'ADD_NEW_WAREHOUSE_SAND_SLURRY';
export const NEW_WAREHOUSE_SAND_SLURRY = 'NEW_WAREHOUSE_SAND_SLURRY';
