export const GET_ALL_WAREHOUSE = 'GET_ALL_WAREHOUSE';
export const ALL_WAREHOUSE = 'ALL_WAREHOUSE';

export const ADD_NEW_WAREHOUSE = 'ADD_NEW_WAREHOUSE';
export const NEW_WAREHOUSE = 'NEW_WAREHOUSE';

// export const GET_ALL_WAREHOUSE = 'GET_ALL_WAREHOUSE'
// export const ALL_WAREHOUSE = 'ALL_WAREHOUSE'
