export const GET_ALL_WAREHOUSE = 'GET_ALL_WAREHOUSE';
export const ALL_WAREHOUSE = 'ALL_WAREHOUSE';

export const ADD_NEW_WAREHOUSE = 'ADD_NEW_WAREHOUSE';
export const NEW_WAREHOUSE = 'NEW_WAREHOUSE';

export const UPDATE_REMAINING_STOCK = 'UPDATE_REMAINING_STOCK';
export const REMAINING_STOCK = 'REMAINING_STOCK';

export const GET_LIST_OF_RESERVED_PRODUCTS = 'GET_LIST_OF_RESERVED_PRODUCTS';
export const LIST_OF_RESERVED_PRODUCTS = 'LIST_OF_RESERVED_PRODUCTS';

export const ADD_NEW_RESERVED_PRODUCT = 'ADD_NEW_RESERVED_PRODUCT';
export const NEW_RESERVED_PRODUCT = 'NEW_RESERVED_PRODUCT';

export const GET_DELETE_PRODUCT_FROM_RESERVED_LIST =
  'GET_DELETE_PRODUCT_FROM_RESERVED_LIST';
export const DELETE_PRODUCT_FROM_RESERVED_LIST = 'DELETE_PRODUCT_FROM_RESERVED_LIST';

export const GET_LIST_OF_ORDERED_PRODUCTION = 'GET_LIST_OF_ORDERED_PRODUCTION';
export const LIST_OF_ORDERED_PRODUCTION = 'LIST_OF_ORDERED_PRODUCTION';

export const ADD_NEW_ORDERED_PRODUCTION = 'ADD_NEW_ORDERED_PRODUCTION';
export const NEW_ORDERED_PRODUCTION = 'NEW_ORDERED_PRODUCTION';

export const GET_LIST_OF_ORDERED_PRODUCTION_OEM = 'GET_LIST_OF_ORDERED_PRODUCTION_OEM';
export const LIST_OF_ORDERED_PRODUCTION_OEM = 'LIST_OF_ORDERED_PRODUCTION_OEM';

export const ADD_NEW_ORDERED_PRODUCTION_OEM = 'ADD_NEW_ORDERED_PRODUCTION_OEM';
export const NEW_ORDERED_PRODUCTION_OEM = 'NEW_ORDERED_PRODUCTION_OEM';
