export const GET_FULL_WAREHOUSE_SAND = 'GET_FULL_WAREHOUSE_SAND';
export const FULL_WAREHOUSE_SAND = 'FULL_WAREHOUSE_SAND';

export const ADD_NEW_WAREHOUSE_SAND = 'ADD_NEW_WAREHOUSE_SAND';
export const NEW_WAREHOUSE_SAND = 'NEW_WAREHOUSE_SAND';

export const UPDATE_NEW_WAREHOUSE_SAND = 'UPDATE_NEW_WAREHOUSE_SAND';
export const UPDATE_WAREHOUSE_SAND = 'UPDATE_WAREHOUSE_SAND';

export const DELETE_WAREHOUSE_SAND = 'DELETE_WAREHOUSE_SAND';
export const NEED_DELETE_WAREHOUSE_SAND = 'NEED_DELETE_WAREHOUSE_SAND';
