export const GET_ALL_WAREHOUSE = 'GET_ALL_WAREHOUSE';
export const ALL_WAREHOUSE = 'ALL_WAREHOUSE';

export const ADD_NEW_WAREHOUSE = 'ADD_NEW_WAREHOUSE';
export const NEW_WAREHOUSE = 'NEW_WAREHOUSE';

export const UPDATE_REMAINING_STOCK = 'UPDATE_REMAINING_STOCK';
export const REMAINING_STOCK = 'REMAINING_STOCK';

export const UPDATE_WAREHOSE_QUANTITYS = 'UPDATE_WAREHOSE_QUANTITYS';
export const WAREHOSE_QUANTITYS = 'WAREHOSE_QUANTITYS';

export const UPDATE_DRY_MIXED_WAREHOSE_QUANTITYS =
  'UPDATE_DRY_MIXED_WAREHOSE_QUANTITYS';

export const UPDATE_ANCHOR_WAREHOSE_QUANTITYS = 'UPDATE_ANCHOR_WAREHOSE_QUANTITYS';

export const UPDATE_TOOL_WAREHOSE_QUANTITYS = 'UPDATE_TOOL_WAREHOSE_QUANTITYS';

export const UPDATE_REL_MAT_WAREHOSE_QUANTITYS = 'UPDATE_REL_MAT_WAREHOSE_QUANTITYS';

export const GET_LIST_OF_RESERVED_PRODUCTS = 'GET_LIST_OF_RESERVED_PRODUCTS';
export const LIST_OF_RESERVED_PRODUCTS = 'LIST_OF_RESERVED_PRODUCTS';

export const ADD_NEW_RESERVED_PRODUCT = 'ADD_NEW_RESERVED_PRODUCT';

export const UPDATE_RESERVED_PRODUCT = 'UPDATE_RESERVED_PRODUCT';
export const UPD_RESERVED_PRODUCT = 'UPD_RESERVED_PRODUCT';

export const GET_DELETE_PRODUCT_FROM_RESERVED_LIST =
  'GET_DELETE_PRODUCT_FROM_RESERVED_LIST';

export const GET_LIST_OF_DRY_MIXED_RESERVED_PRODUCTS =
  'GET_LIST_OF_DRY_MIXED_RESERVED_PRODUCTS';
export const LIST_OF_DRY_MIXED_RESERVED_PRODUCTS =
  'LIST_OF_DRY_MIXED_RESERVED_PRODUCTS';

export const ADD_NEW_DRY_MIXED_RESERVED_PRODUCT =
  'ADD_NEW_DRY_MIXED_RESERVED_PRODUCT';

export const UPDATE_DRY_MIXED_RESERVED_PRODUCT = 'UPDATE_DRY_MIXED_RESERVED_PRODUCT';

export const GET_DELETE_PRODUCT_FROM_DRY_MIXED_RESERVED_LIST =
  'GET_DELETE_PRODUCT_FROM_DRY_MIXED_RESERVED_LIST';

export const GET_LIST_OF_ANCHOR_RESERVED_PRODUCTS =
  'GET_LIST_OF_ANCHOR_RESERVED_PRODUCTS';
export const LIST_OF_ANCHOR_RESERVED_PRODUCTS = 'LIST_OF_ANCHOR_RESERVED_PRODUCTS';

export const ADD_NEW_ANCHOR_RESERVED_PRODUCT = 'ADD_NEW_ANCHOR_RESERVED_PRODUCT';

export const UPDATE_ANCHOR_RESERVED_PRODUCT = 'UPDATE_ANCHOR_RESERVED_PRODUCT';

export const GET_DELETE_PRODUCT_FROM_ANCHOR_RESERVED_LIST =
  'GET_DELETE_PRODUCT_FROM_ANCHOR_RESERVED_LIST';

export const GET_LIST_OF_TOOL_RESERVED_PRODUCTS =
  'GET_LIST_OF_TOOL_RESERVED_PRODUCTS';
export const LIST_OF_TOOL_RESERVED_PRODUCTS = 'LIST_OF_TOOL_RESERVED_PRODUCTS';

export const ADD_NEW_TOOL_RESERVED_PRODUCT = 'ADD_NEW_TOOL_RESERVED_PRODUCT';

export const UPDATE_TOOL_RESERVED_PRODUCT = 'UPDATE_TOOL_RESERVED_PRODUCT';

export const GET_DELETE_PRODUCT_FROM_TOOL_RESERVED_LIST =
  'GET_DELETE_PRODUCT_FROM_TOOL_RESERVED_LIST';

export const GET_LIST_OF_REL_MAT_PRODUCTS = 'GET_LIST_OF_REL_MAT_PRODUCTS';
export const LIST_OF_REL_MAT_PRODUCTS = 'LIST_OF_REL_MAT_PRODUCTS';

export const ADD_NEW_REL_MAT_RESERVED_PRODUCT = 'ADD_NEW_REL_MAT_RESERVED_PRODUCT';

export const UPDATE_REL_MAT_PRODUCT = 'UPDATE_REL_MAT_PRODUCT';

export const GET_DELETE_PRODUCT_FROM_REL_MAT_LIST =
  'GET_DELETE_PRODUCT_FROM_REL_MAT_LIST';

export const GET_LIST_OF_ORDERED_PRODUCTION = 'GET_LIST_OF_ORDERED_PRODUCTION';
export const LIST_OF_ORDERED_PRODUCTION = 'LIST_OF_ORDERED_PRODUCTION';

export const GET_AUTOCLAVE_CALENDAR = 'GET_AUTOCLAVE_CALENDAR';
export const AUTOCLAVE_CALENDAR = 'AUTOCLAVE_CALENDAR';

export const ADD_NEW_AUTOCLAVE_CALENDAR = 'ADD_NEW_AUTOCLAVE_CALENDAR';
export const NEW_AUTOCLAVE_CALENDAR = 'NEW_AUTOCLAVE_CALENDAR';

export const ADD_NEW_ORDERED_PRODUCTION = 'ADD_NEW_ORDERED_PRODUCTION';

export const UPDATE_ORDERED_PRODUCTION = 'UPDATE_ORDERED_PRODUCTION';
export const UPDATE_ORDERED_PRODUCTION_OEM = 'UPDATE_ORDERED_PRODUCTION_OEM';

export const GET_LIST_OF_ORDERED_PRODUCTION_OEM =
  'GET_LIST_OF_ORDERED_PRODUCTION_OEM';
export const LIST_OF_ORDERED_PRODUCTION_OEM = 'LIST_OF_ORDERED_PRODUCTION_OEM';

export const ADD_NEW_ORDERED_PRODUCTION_OEM = 'ADD_NEW_ORDERED_PRODUCTION_OEM';

export const GET_RAW_MATERIALS_WAREHOUSE = 'GET_RAW_MATERIALS_WAREHOUSE';
export const RAW_MATERIALS_WAREHOUSE = 'RAW_MATERIALS_WAREHOUSE';

export const UPDATE_NEW_RAW_MATERIALS_WAREHOUSE =
  'UPDATE_NEW_RAW_MATERIALS_WAREHOUSE';
export const UPDATE_RAW_MATERIALS_WAREHOUSE = 'UPDATE_RAW_MATERIALS_WAREHOUSE';

export const UPDATE_NEW_RAW_MATERIALS_CONSUMPTION_RAW_MATERIALS_WAREHOUSE =
  'UPDATE_NEW_RAW_MATERIALS_CONSUMPTION_RAW_MATERIALS_WAREHOUSE';
export const UPDATE_RAW_MATERIALS_CONSUMPTION_RAW_MATERIALS_WAREHOUSE =
  'UPDATE_RAW_MATERIALS_CONSUMPTION_RAW_MATERIALS_WAREHOUSE';

export const UPDATE_RAW_MATERIALS_WAREHOUSE_SUCCESS =
  'UPDATE_RAW_MATERIALS_WAREHOUSE_SUCCESS';
export const UPDATE_RAW_MATERIALS_WAREHOUSE_FAILURE =
  'UPDATE_RAW_MATERIALS_WAREHOUSE_FAILURE';

export const GET_ALL_WAREHOUSE_MANAGER_TRAILER = 'GET_ALL_WAREHOUSE_MANAGER_TRAILER';
export const ALL_WAREHOUSE_MANAGER_TRAILER = 'ALL_WAREHOUSE_MANAGER_TRAILER';

export const ADD_NEW_WAREHOUSE_MANAGER_TRAILER = 'ADD_NEW_WAREHOUSE_MANAGER_TRAILER';
